[FormatVersion]
Version = 2.0

[Tools]
LabVIEWPath = C:\Program Files\National Instruments\LabVIEW 2024
VivadoToolsPath = C:\NIFPGA\programs\Vivado2021_1
VivadoTclScriptsFolder = ../common/TCL
ModelSimToolsPath = 
XilinxSimLibPath =


[GeneralSettings]
TargetFamily = FlexRIO
BaseTarget = PXIe-7981
Dependencies = ../../dependencies.toml


[VivadoProjectSettings]
TopLevelEntity = MacallanTop
FPGAPart = xcku035-ffva1156-2-e
VivadoProjectPath = VivadoProject/My7981Proj.xpr
VivadoProjectFilesLists =
    ../../deps/flexrio/targets/pxie-7981/vivadoprojectdeps.txt
    vivadoprojectsources.txt
ConstraintsTemplates =
    ../../deps/flexrio/targets/pxie-7981/xdc/constraints.xdc
CustomConstraintsFile = xdc/custom_constraints.xdc
VivadoProjectConstraintsFiles =
    ../../deps/flexrio/targets/pxie-7981/xdc/constraints_place.xdc
    objects/xdc/constraints.xdc

UseGeneratedLVWindowFiles = True
TheWindowFolder = lvWindowNetlist
CodeGenerationResultsStub = ../../deps/flexrio/targets/pxie-7981/lvFpgaTarget/CodeGenerationResultsStub.lvtxt


[LVFPGATargetSettings]
# Inputs
LVTargetBoardIO = lvFpgaTarget/LVTargetBoardIO.csv
IncludeCLIPSocket = False
IncludeLVTargetBoardIO = False
LVTargetName = PXIe-7981Custom
LVTargetGUID = 7420a8be-d53b-458d-8bd6-95df6f1c53df
LVTargetInstallFolder = C:\Program Files\NI\LVAddons\flexrioii\1\Targets\NI\FPGA\RIO\79XXR
LVTargetConstraintsFiles =
    ../../deps/flexrio/targets/pxie-7981/xdc/constraints.xdc
    ../../deps/flexrio/targets/pxie-7981/xdc/constraints_place.xdc
LVTargetMenusFolder =
    ../../deps/flexrio/targets/common/lvFpgaTarget/targetpluginmenus
LVTargetInfoIni =
    ../../deps/flexrio/targets/pxie-7981/lvFpgaTarget/TargetInfo.ini
LvTargetExcludeFiles = ../../deps/flexrio/targets/pxie-7981/lvtargetexcludefiles.txt
MaxHdlRegOffset = 16

# Templates
WindowVhdlTemplates =
    ../../deps/flexrio/targets/pxie-7981/rtl-lvfpga/lvgen/TheWindow.vhd.mako
    rtl-lvfpga/TheLvWindowFlatWrapper.vhd.mako
    rtl-lvfpga/PkgTheLvWindowFlatWrapper.vhd.mako
TargetXMLTemplates =
    ../../deps/flexrio/targets/pxie-7981/lvFpgaTarget/Resource.xml.mako
    ../../deps/flexrio/targets/pxie-7981/lvFpgaTarget/Macallan7981.xml.mako

# Outputs
WindowVhdlOutputFolder = objects/GeneratedHDL
BoardIOSignalAssignmentsExample = objects/GeneratedHDL/BoardIOSignalAssignmentsExample.vhd
LVTargetPluginFolder = objects/LVTargetPlugin/PXIe-7981Custom
BoardIOXML = objects/LVTargetPlugin/PXIe-7981Custom/boardio.xml
ClockXML = objects/LVTargetPlugin/PXIe-7981Custom/CustomClocks.xml


[CLIPMigrationSettings]
# Inputs
CLIPXML =
CLIPHDLTop =
CLIPXDCIn =
CLIPInstancePath =

# Outputs
LVTargetBoardIO = lvFpgaTarget/LVTargetBoardIO.csv
CLIPInstantiationExample = objects/CLIPMigration/CLIPInstantiationExample.vhd
CLIPtoWindowSignalDefinitions = objects/CLIPMigration/CLIPtoWindowSignalDefinitions.vhd
CLIPXDCOutFolder = objects/CLIPMigration/xdc

[LVWindowNetlistSettings]
# Inputs
VivadoProjectExportXPR = C:\temp\customwindow\7981_VPE\VivadoProject\Running6.xpr

# Outputs
TheWindowFolder = objects/TheWindow

[ModelSimProjectSettings]
ModelSimProjectPath = ModelSimProject/My7981Proj.mpf
