-------------------------------------------------------------------------------
--
-- File: UserHdlTestCore.vhd
--
-------------------------------------------------------------------------------
-- (c) 2026 Copyright National Instruments Corporation
--
-- SPDX-License-Identifier: MIT
-------------------------------------------------------------------------------
--
-- Purpose:
--   Generic, board-agnostic test driver for UserHdl. It exercises only the
--   register port and the DMA FIFO stream ends, so it is identical for every
--   target. It generates the BusClk / DmaClk, drives the resets, register
--   port and the Writer/Reader DMA stream ends, and runs the single-sourced
--   stimulus from work.PkgUserHdlTest.
--
--   The DUT (work.UserHdl) is instantiated by each target's tb_UserHdl, which
--   also ties off that target's board IO. This core connects to the DUT purely
--   through its register/FIFO ports, so it carries no board-IO knowledge.
--
-------------------------------------------------------------------------------

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

library work;
  use work.PkgNiUtilities.all;
  use work.PkgCommunicationInterface.all;
  use work.PkgDmaPortDmaFifos.all;
  use work.PkgUserHdl.all;
  use work.PkgUserHdlTest.all;

entity UserHdlTestCore is
  generic (
    -- Board signature reported by the common Signature register.
    kSignature : std_logic_vector(31 downto 0);
    -- Number of DIO lines this target exposes (0 = no DIO test). 8 for the Aux
    -- and narrow base-board DIO, 32 for the wide base-board DIO.
    kNumDioLines : natural := 0
  );
  port (
    -- Clocks generated by this core and driven into the DUT. Defaulted to '0'
    -- so the free-running 'not BusClk' generators start cleanly, and driven
    -- directly (no intermediate signal) so the DUT sees them with zero delta
    -- skew relative to the stimulus.
    BusClk : out std_logic := '0';
    DmaClk : out std_logic := '0';

    -- Resets driven into the DUT.
    aBusReset : out boolean;
    aDiagramReset : out std_logic;

    -- Host register port.
    bRegPortIn : out RegPortIn_t;
    bRegPortOut : in RegPortOut_t;

    -- Writer FIFO DMA stream end (FPGA-to-Host): the stimulus enables and
    -- drains this end to observe host-pushed samples.
    dWriterInputStreamInterfaceToFifo : out InputStreamInterfaceToFifo_t;
    dWriterInputStreamInterfaceFromFifo : in InputStreamInterfaceFromFifo_t;

    -- Reader FIFO DMA stream end (Host-to-FPGA): the stimulus enables and
    -- writes one known sample to be popped at the host end.
    dReaderOutputStreamInterfaceToFifo : out OutputStreamInterfaceToFifo_t;
    dReaderOutputStreamInterfaceFromFifo : in OutputStreamInterfaceFromFifo_t
  );
end entity UserHdlTestCore;

architecture sim of UserHdlTestCore is

  constant kBusClkPeriod : time := 10 ns;
  constant kDmaClkPeriod : time := 8 ns;

  signal TestDone : boolean := false;

begin

  BusClk <= not BusClk after kBusClkPeriod / 2 when not TestDone else '0';
  DmaClk <= not DmaClk after kDmaClkPeriod / 2 when not TestDone else '0';

  Stimulus : process
  begin
    RunUserHdlTest(
      kSignature => kSignature,
      kNumDioLines => kNumDioLines,
      BusClk => BusClk,
      DmaClk => DmaClk,
      aBusReset => aBusReset,
      aDiagramReset => aDiagramReset,
      bRegPortIn => bRegPortIn,
      bRegPortOut => bRegPortOut,
      dWriterInputStreamInterfaceToFifo => dWriterInputStreamInterfaceToFifo,
      dWriterInputStreamInterfaceFromFifo => dWriterInputStreamInterfaceFromFifo,
      dReaderOutputStreamInterfaceToFifo => dReaderOutputStreamInterfaceToFifo,
      dReaderOutputStreamInterfaceFromFifo => dReaderOutputStreamInterfaceFromFifo,
      TestDone => TestDone
    );
    wait;
  end process;

end architecture sim;
