# githubvisible=true

[GeneralSettings]
TargetFamily = FlexRIO
BaseTarget = PXIe-7903
LabVIEWPath = C:\Program Files\National Instruments\LabVIEW 2024


[VivadoProjectSettings]
TopLevelEntity = SasquatchTopTemplate
# note: no spaces allowed in project name, do not include .xpr extension
VivadoProjectName = MySasquatchProj
VivadoToolsPath = C:/NIFPGA/programs/Vivado2021_1
VivadoProjectFilesLists =
    ../../deps/flexrio/targets/pxie-7903/vivadoprojectdeps.txt
    vivadoprojectsources.txt
ConstraintsTemplates = 
    ../../deps/flexrio/targets/pxie-7903/xdc/constraints.xdc_template
CustomConstraintsFile = xdc/custom_constraints.xdc
VivadoProjectConstraintsFiles =
    ../../deps/flexrio/targets/pxie-7903/xdc/constraints_place.xdc
    objects/xdc/constraints.xdc
VivadoTclScriptsFolder = ../../deps/flexrio/targets/pxie-7903/TCL
UseGeneratedLVWindowFiles = True
TheWindowFolder = objects/TheWindowRunning
CodeGenerationResultsStub = ../../deps/flexrio/targets/pxie-7903/lvFpgaTarget/CodeGenerationResultsStub.lvtxt


[LVFPGATargetSettings]
# Inputs
LVTargetBoardIO = lvFpgaTarget/LVTargetBoardIO.csv
# *** TEMPORARY WORKAROUND ***
# IncludeCLIPSocket must be set to True because LabVIEW FPGA and the FlexRIO driver looks for it in the target plugin when generating
# constants that go into a package file called PkgLvFpgaConst.vhd that is created during LV FPGA code generation.  This is a temporary
# workaround until the FlexRIO driver is updated to properly generate these constants even when the CLIP socket is not included on the
# target plugin.
IncludeCLIPSocket = True
IncludeLVTargetBoardIO = False
LVTargetName = PXIe-7903Custom
LVTargetGUID = 4ad9cfc3-df38-4086-9d0b-02bca6b24719
LVTargetInstallFolder = C:\Program Files\NI\LVAddons\flexrioii\1\Targets\NI\FPGA\RIO\79XXR
LVTargetConstraintsFiles =
    ../../deps/flexrio/targets/pxie-7903/xdc/constraints.xdc_template
    ../../deps/flexrio/targets/pxie-7903/xdc/constraints_place.xdc
LVTargetMenusFolder =
    ../../deps/flexrio/targets/common/lvFpgaTarget/targetpluginmenus
LVTargetInfoIni =
    ../../deps/flexrio/targets/pxie-7903/lvFpgaTarget/TargetInfo.ini
LvTargetExcludeFiles = ../../deps/flexrio/targets/pxie-7903/lvtargetexcludefiles.txt
NumHdlRegisters = 4

# Templates
WindowVhdlTemplates = 
    ../../deps/flexrio/targets/pxie-7903/rtl-lvfpga/lvgen/TheWindow.vhd.mako
    ../../deps/flexrio/targets/pxie-7903/rtl-lvfpga/TheWindowFlatWrapper.vhd.mako
    ../../deps/flexrio/targets/pxie-7903/rtl-lvfpga/PkgTheWindowFlatWrapper.vhd.mako
TargetXMLTemplates =
    ../../deps/flexrio/targets/pxie-7903/lvFpgaTarget/Resource.xml.mako 
    ../../deps/flexrio/targets/pxie-7903/lvFpgaTarget/Sasquatch7903.xml.mako

# Outputs
WindowVhdlOutputFolder = objects/GeneratedHDL
BoardIOSignalAssignmentsExample = objects/GeneratedHDL/BoardIOSignalAssignmentsExample.vhd
LVTargetPluginFolder = objects/LVTargetPlugin/PXIe-7903Custom
BoardIOXML = objects/LVTargetPlugin/PXIe-7903Custom/boardio.xml
ClockXML = objects/LVTargetPlugin/PXIe-7903Custom/CustomClocks.xml


[CLIPMigrationSettings]
# Inputs
CLIPXML =
CLIPHDLTop =
CLIPXDCIn =
CLIPInstancePath =

# Outputs
LVTargetBoardIO = lvFpgaTarget/LVTargetBoardIO.csv
CLIPInstantiationExample = objects/CLIPMigration/CLIPInstantiationExample.vhd
CLIPtoWindowSignalDefinitions = objects/CLIPMigration/CLIPtoWindowSignalDefinitions.vhd
CLIPXDCOutFolder = objects/CLIPMigration/xdc

[LVWindowNetlistSettings]
# Inputs
VivadoProjectExportXPR = C:\temp\GH8_Custom_RunVI_VPE\VivadoProject\RunningVI.xpr

# Outputs
TheWindowFolder = objects/TheWindowRunning
