[FormatVersion]
Version = 2.0

[Tools]
LabVIEWPath = C:\Program Files\National Instruments\LabVIEW 2024
VivadoToolsPath = C:/NIFPGA/programs/Vivado2021_1
VivadoTclScriptsFolder = ../common/TCL
ModelSimToolsPath = 
XilinxSimLibPath =


[GeneralSettings]
TargetFamily = FlexRIO
BaseTarget = PXIe-7903
Dependencies = ../../dependencies.toml


[VivadoProjectSettings]
TopLevelEntity = SasquatchTopTemplate
FPGAPart = xcvu11p-flgb2104-2-e
VivadoProjectPath = VivadoProject/My7903AuroraProj.xpr
VivadoProjectFilesLists =
    ../../deps/flexrio/targets/pxie-7903/vivadoprojectdeps.txt
    vivadoprojectsources.txt
    vivadoprojectclipsources.txt
ConstraintsTemplates = 
    ../../deps/flexrio/targets/pxie-7903/xdc/constraints.xdc_template
CustomConstraintsFile = xdc/custom_constraints.xdc
VivadoProjectConstraintsFiles =
    ../../deps/flexrio/targets/pxie-7903/xdc/constraints_place.xdc
    objects/xdc/constraints.xdc

UseGeneratedLVWindowFiles = False
TheWindowFolder = objects/TheWindow
CodeGenerationResultsStub = lvFpgaTarget/CodeGenerationResultsStub.lvtxt


[LVFPGATargetSettings]
# Inputs
LVTargetBoardIO = lvFpgaTarget/LVTargetBoardIO.csv
IncludeCLIPSocket = False
IncludeLVTargetBoardIO = True
LVTargetName = PXIe-7903Aurora
LVTargetGUID = 8943868e-fc0c-4e48-a2e9-1ebce7779d5c
LVTargetInstallFolder = C:\Program Files\NI\LVAddons\flexrioii\1\Targets\NI\FPGA\RIO\79XXR
LVTargetConstraintsFiles =
    ../../deps/flexrio/targets/pxie-7903/xdc/constraints.xdc_template
    ../../deps/flexrio/targets/pxie-7903/xdc/constraints_place.xdc
LVTargetMenusFolder =
    ../../deps/flexrio/targets/common/lvFpgaTarget/targetpluginmenus
LVTargetInfoIni =
    ../../deps/flexrio/targets/pxie-7903/lvFpgaTarget/TargetInfo.ini
LvTargetExcludeFiles = ../../deps/flexrio/targets/pxie-7903/lvtargetexcludefiles.txt
MaxHdlRegOffset = 0

# Templates
WindowVhdlTemplates = 
    ../../deps/flexrio/targets/pxie-7903/rtl-lvfpga/lvgen/TheWindow.vhd.mako
    rtl-lvfpga/TheLvWindowFlatWrapper.vhd.mako
    rtl-lvfpga/PkgTheLvWindowFlatWrapper.vhd.mako
TargetXMLTemplates =
    ../../deps/flexrio/targets/pxie-7903/lvFpgaTarget/Resource.xml.mako 
    ../../deps/flexrio/targets/pxie-7903/lvFpgaTarget/Sasquatch7903.xml.mako

# Outputs
WindowVhdlOutputFolder = objects/GeneratedHDL
BoardIOSignalAssignmentsExample = objects/GeneratedHDL/BoardIOSignalAssignmentsExample.vhd
LVTargetPluginFolder = objects/LVTargetPlugin/PXIe-7903Aurora
BoardIOXML = objects/LVTargetPlugin/PXIe-7903Aurora/boardio.xml
ClockXML = objects/LVTargetPlugin/PXIe-7903Aurora/CustomClocks.xml


[CLIPMigrationSettings]
# Inputs
CLIPXML = ../../dependencies/githubdeps/ni.hw-flexrio.sasquatch_aurora64b66b_clip.25.5.0.11-ci-passed-main-f/aurora64b66b_framing_crcx4_28p0GHz/CLIP/aurora64b66b_framing_crcx4_28p0GHz/Source/xml/PXIe7903_Aurora64b66b_Framing_Crcx4_28p0GHz.xml
CLIPHDLTop = ../../dependencies/githubdeps/ni.hw-flexrio.sasquatch_aurora64b66b_clip.25.5.0.11-ci-passed-main-f/aurora64b66b_framing_crcx4_28p0GHz/CLIP/aurora64b66b_framing_crcx4_28p0GHz/Source/vhdl/UserRTL_PXIe7903_Aurora64b66b_Framing_Crcx4_28p0GHz.vhd
CLIPXDCIn = 
    ../../dependencies/githubdeps/ni.hw-flexrio.sasquatch_aurora64b66b_clip.25.5.0.11-ci-passed-main-f/aurora64b66b_framing_crcx4_28p0GHz/CLIP/aurora64b66b_framing_crcx4_28p0GHz/Source/xdc/PXIe7903_Aurora64b66b_Framing_Crcx4_28p0GHz.xdc
    ../../dependencies/githubdeps/ni.hw-flexrio.sasquatch_aurora64b66b_clip.25.5.0.11-ci-passed-main-f/aurora64b66b_framing_crcx4_28p0GHz/CLIP/aurora64b66b_framing_crcx4_28p0GHz/Source/xdc/PXIe7903_microblaze_debug_place.xdc
CLIPInstancePath = UserRTL_PXIe7903_Aurora64b66b_Framing_Crcx4_28p0GHz_inst

# Outputs
LVTargetBoardIO = lvFpgaTarget/LVTargetBoardIO.csv
CLIPInstantiationExample = objects/CLIPMigration/CLIPInstantiationExample.vhd
CLIPtoWindowSignalDefinitions = objects/CLIPMigration/CLIPtoWindowSignalDefinitions.vhd
CLIPXDCOutFolder = objects/CLIPMigration/xdc

[LVWindowNetlistSettings]
# Inputs
VivadoProjectExportXPR = C:\temp\GH9_AC_VPE_A\VivadoProject\Top_FPGA_dash_2_dash_port.xpr

# Outputs
TheWindowFolder = objects/TheWindow

[ModelSimProjectSettings]
ModelSimProjectPath = ModelSimProject/My7903AuroraProj.mpf
