[FormatVersion]
Version = 2.0

[Tools]
LabVIEWPath = C:\Program Files\National Instruments\LabVIEW 2024
VivadoToolsPath = C:\NIFPGA\programs\Vivado2021_1
VivadoTclScriptsFolder = ../common/TCL
ModelSimToolsPath = 
XilinxSimLibPath =


[GeneralSettings]
TargetFamily = FlexRIO
BaseTarget = PXIe-7903-DDR1280
Dependencies = ../../dependencies.toml


[VivadoProjectSettings]
TopLevelEntity = SasquatchTopTemplate
FPGAPart = xcvu11p-flgb2104-2-e
VivadoProjectPath = VivadoProject/My7903Ddr1280Proj.xpr
VivadoProjectFilesLists =
    ../../deps/flexrio/targets/pxie-7903-ddr1280/vivadoprojectdeps.txt
    vivadoprojectsources.txt
ConstraintsTemplates = 
    ../../deps/flexrio/targets/pxie-7903-ddr1280/xdc/constraints.xdc_template
CustomConstraintsFile = xdc/custom_constraints.xdc
VivadoProjectConstraintsFiles =
    ../../deps/flexrio/targets/pxie-7903-ddr1280/xdc/constraints_place.xdc
    objects/xdc/constraints.xdc

UseGeneratedLVWindowFiles = True
TheWindowFolder = lvWindowNetlist
CodeGenerationResultsStub = ../../deps/flexrio/targets/pxie-7903-ddr1280/lvFpgaTarget/CodeGenerationResultsStub.lvtxt


[LVFPGATargetSettings]
# Inputs
LVTargetBoardIO = lvFpgaTarget/LVTargetBoardIO.csv
IncludeCLIPSocket = False
IncludeLVTargetBoardIO = False
LVTargetName = PXIe-7903-DDR1280Custom
LVTargetGUID = 92f09af2-f6c0-4f93-a9c3-209f1f4b37b7
LVTargetInstallFolder = C:\Program Files\NI\LVAddons\flexrioii\1\Targets\NI\FPGA\RIO\79XXR
LVTargetConstraintsFiles =
    ../../deps/flexrio/targets/pxie-7903-ddr1280/xdc/constraints.xdc_template
    ../../deps/flexrio/targets/pxie-7903-ddr1280/xdc/constraints_place.xdc
LVTargetMenusFolder =
    ../../deps/flexrio/targets/common/lvFpgaTarget/targetpluginmenus
LVTargetInfoIni =
    ../../deps/flexrio/targets/pxie-7903-ddr1280/lvFpgaTarget/TargetInfo.ini
LvTargetExcludeFiles = ../../deps/flexrio/targets/pxie-7903-ddr1280/lvtargetexcludefiles.txt
MaxHdlRegOffset = 16

# Templates
WindowVhdlTemplates = 
    ../../deps/flexrio/targets/pxie-7903-ddr1280/rtl-lvfpga/lvgen/TheWindow.vhd.mako
    rtl-lvfpga/TheLvWindowFlatWrapper.vhd.mako
    rtl-lvfpga/PkgTheLvWindowFlatWrapper.vhd.mako
TargetXMLTemplates =
    ../../deps/flexrio/targets/pxie-7903-ddr1280/lvFpgaTarget/Resource.xml.mako 
    ../../deps/flexrio/targets/pxie-7903-ddr1280/lvFpgaTarget/Sasquatch7903DDR1280.xml.mako

# Outputs
WindowVhdlOutputFolder = objects/GeneratedHDL
BoardIOSignalAssignmentsExample = objects/GeneratedHDL/BoardIOSignalAssignmentsExample.vhd
LVTargetPluginFolder = objects/LVTargetPlugin/PXIe-7903-DDR1280Custom
BoardIOXML = objects/LVTargetPlugin/PXIe-7903-DDR1280Custom/boardio.xml
ClockXML = objects/LVTargetPlugin/PXIe-7903-DDR1280Custom/CustomClocks.xml


[CLIPMigrationSettings]
# Inputs
CLIPXML =
CLIPHDLTop =
CLIPXDCIn =
CLIPInstancePath =

# Outputs
LVTargetBoardIO = lvFpgaTarget/LVTargetBoardIO.csv
CLIPInstantiationExample = objects/CLIPMigration/CLIPInstantiationExample.vhd
CLIPtoWindowSignalDefinitions = objects/CLIPMigration/CLIPtoWindowSignalDefinitions.vhd
CLIPXDCOutFolder = objects/CLIPMigration/xdc

[LVWindowNetlistSettings]
# Inputs
VivadoProjectExportXPR = C:\temp\customwindow\7903_DDR1280_VPE\VivadoProject\Running5.xpr

# Outputs
TheWindowFolder = objects/TheWindow

[ModelSimProjectSettings]
ModelSimProjectPath = ModelSimProject/My7903Ddr1280Proj.mpf
