# githubvisible=true

# Auto-generated by nihdl check-syntax
set pre_synth_tcl {PRE_SYNTH_TCL_PATH}
open_project {PROJECT_FILE_NAME}
update_compile_order -fileset sources_1
set_property top TOP_ENTITY_NAME [current_fileset]

if {[file exists $pre_synth_tcl]} {
    source $pre_synth_tcl
}

if {[catch {
    synth_design -rtl -top TOP_ENTITY_NAME -part FPGA_PART_NAME -name nihdl_check_syntax
} result options]} {
    puts stderr $result
    if {[dict exists $options -errorinfo]} {
        puts stderr [dict get $options -errorinfo]
    }
    puts "NIHDL_CHECK_SYNTAX=FAILED"
    exit 1
}

puts "NIHDL_CHECK_SYNTAX=PASSED"
exit 0
