-------------------------------------------------------------------------------
--
-- File: DmaPortOutStrmFifo.vhd
-- Author: Haider Khan
-- Original Project: CHInCh Interface
-- Date: 11 January 2008
--
-------------------------------------------------------------------------------
-- (c) 2008 Copyright National Instruments Corporation
-- All Rights Reserved
-- National Instruments Internal Information
-------------------------------------------------------------------------------
--
-- Purpose: Data packing FIFO for OUT streams.
--
-------------------------------------------------------------------------------

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

library work;
  use work.PkgNiUtilities.all;
  use work.PkgDmaPortDataPackingFifo.all;
  use work.PkgNiDma.all;
  use work.PkgNiDmaConfig.all;

entity DmaPortOutStrmFifo is
  generic (
    --kAddressWidth:  This is the width of the address bits feeding the FIFO.
    --                Each FIFO location representing one data bus width word.
    kAddressWidth : integer := 8;
    --kSampleSize:  This represents the sample size rounded up to the closer
    --              standard data type.
    kSampleSize : natural := 8;
    --kNumOfSamplesPerRead:  This is the number of samples read from the FIFO on the VI side;
    kNumOfSamplesPerRead : natural := 1;
    --kRdPortWidth:  The read port width specifies the data width read from the FIFO
    --               on the user side. This take in consideration the standard
    --               sample size and the number of samples poped in one read cycle.
    kRdPortWidth : integer := 8;
    --kFifoCountWidth:  The number of bits needed to represent the number of samples
    --                  that fit in the FIFO.
    kFifoCountWidth : natural;
    --kCorrelatedDataWidth:  This is the width of any correlated data that is to be
    --                       transferred from the IClk domain to the OClk domain to
    --                       ensure that the data matches the delay for the full count.
    kCorrelatedDataWidth : integer := 0;
    --kCorrelatedDataResetValue:  The value that the correlated data should reset to.
    kCorrelatedDataResetValue : std_logic_vector
  );
  port (
    --aReset:   Serves as an asynchronous reset to this module.  
    aReset : in boolean;

    -------------------------------------------------------------------------------------
    --INPUT PORT:
    -------------------------------------------------------------------------------------
    --The input port is the port that is exposed to the DMA control logic moving
    --receiving data from the bus. This side of the port is always 64-bits and is not 
    --configureable, unlike the Output port.

    --IClk:     This is the input clock to this module. 
    IClk : in std_logic;
    --iReset:   Synchronous reset for the input circuitry.
    iReset : in boolean;
    --iWrite:   This signal is used for pushing data into the FIFO.
    iWrite : in boolean;
    --iWriteEnables:    These write enables are generated by the DMA controller 
    --                  to control the contents being written into the BRAM.
    --                  The enables are byte wide and for this design the BRAM
    --                  is always written with data bus words even if the FIFO width
    --                  is wider than the data bus.
    iWriteEnables : in NiDmaByteEnable_t;
    --iWriteLengthInBytes:   The number of bytes that are being written when the
    --                       write signal is strobed.
    iWriteLengthInBytes : in NiDmaBusByteCount_t;
    --iDataIn:  Data that needs to be written to the FIFO.
    iDataIn : in NiDmaData_t;
    --iCorrelatedDataIn:  The data that will be correlated with the FIFO count.  It is
    --                    clocked from the IClk to OClk domain at the same rate as the
    --                    FIFO count.
    iCorrelatedDataIn : in std_logic_vector(kCorrelatedDataWidth-1 downto 0);
    --iEmptyCount:    The empty count represents the number of empty spaces available 
    --                in the FIFO.
    iEmptyCount : out unsigned(kFifoCountWidth-1 downto 0);
    --iRsrvWriteSpaces:  This is the boolean used to strobe in spaces that are being
    --                   reserved.  Spaces are reserved whenever read request packets
    --                   are sent.
    iRsrvWriteSpaces : in boolean;
    --iReqWriteSpaces:   This is the number of spaces that are being reserved when the
    --                   RsrvWriteSpaces signal is strobed.
    iReqWriteSpaces : in unsigned(kFifoCountWidth-1 downto 0);
    --iRsrvdSpacesFilled:  This boolean indicates when all the spaces that were reserved
    --                     have been filled with data.  This is used to know when we
    --                     should not expect any more read response packets.
    iRsrvdSpacesFilled : out boolean;

    -------------------------------------------------------------------------------------
    --OUTPUT PORT:
    -------------------------------------------------------------------------------------
    --The output port is the port that is exposed to the user and is configureable
    --to support data packing.

    --OClk:     This is the output port clock.
    OClk : in std_logic;
    --oReset:   Synchronous reset for the output circuitry in this module.
    oReset : in boolean;    
    --oRead:    This signal is used for incrementing the read pointers.
    --          It is upto the pop buffer to make sure that the oRead is only asserted
    --          when there truly needs to be a pop from the FIFO.
    oRead : in boolean;
    --oDataOut: Data read from the FIFO.
    oDataOut : out std_logic_vector(kRdPortWidth-1 downto 0);
    --oCorrelatedDataOut:  The correlated data out.  It is clocked from the IClk to OClk
    --                     domain at the same rate as the FIFO count.
    oCorrelatedDataOut : out std_logic_vector(kCorrelatedDataWidth-1 downto 0);
    --oFullCount:     The full count represents the number of spaces that have been
    --                already filled in the FIFO.    
    oFullCount : out unsigned(kFifoCountWidth-1 downto 0)
  );
end DmaPortOutStrmFifo;

architecture rtl of DmaPortOutStrmFifo is

  --vhook_sigstart
  signal iAddr: unsigned(kAddressWidth-1 downto 0);
  signal oAddr: unsigned(kFifoCountWidth-1 downto 0);
  --vhook_sigend

begin

  -----------------------------------------------------------------------------
  -- Instantiate the FifoFlags module
  -----------------------------------------------------------------------------

  --vhook_e DmaPortOutStrmFifoFlags
  --vhook_a iReqWriteSamples iReqWriteSpaces
  DmaPortOutStrmFifoFlagsx: entity work.DmaPortOutStrmFifoFlags (rtl)
    generic map (
      kAddressWidth             => kAddressWidth,              -- in  natural := 6
      kSampleSize               => kSampleSize,                -- in  natural := 8
      kNumOfSamplesPerRead      => kNumOfSamplesPerRead,       -- in  natural := 1
      kRdPortWidth              => kRdPortWidth,               -- in  natural := 8
      kFifoCountWidth           => kFifoCountWidth,            -- in  natural
      kCorrelatedDataWidth      => kCorrelatedDataWidth,       -- in  integer := 0
      kCorrelatedDataResetValue => kCorrelatedDataResetValue)  -- in  std_logic_vector
    port map (
      aReset              => aReset,               -- in  boolean
      IClk                => IClk,                 -- in  std_logic
      iReset              => iReset,               -- in  boolean
      iWrite              => iWrite,               -- in  boolean
      iAddr               => iAddr,                -- out unsigned(kAddressWidth-1 downto
      iCorrelatedDataIn   => iCorrelatedDataIn,    -- in  std_logic_vector(kCorrelatedDat
      iWriteLengthInBytes => iWriteLengthInBytes,  -- in  NiDmaBusByteCount_t
      iRsrvWriteSpaces    => iRsrvWriteSpaces,     -- in  boolean
      iReqWriteSamples    => iReqWriteSpaces,      -- in  unsigned(kFifoCountWidth-1 down
      iRsrvdSpacesFilled  => iRsrvdSpacesFilled,   -- out boolean
      OClk                => OClk,                 -- in  std_logic
      oReset              => oReset,               -- in  boolean
      oRead               => oRead,                -- in  boolean
      oAddr               => oAddr,                -- out unsigned(kFifoCountWidth-1 down
      oCorrelatedDataOut  => oCorrelatedDataOut,   -- out std_logic_vector(kCorrelatedDat
      iEmptyCount         => iEmptyCount,          -- out unsigned(kFifoCountWidth-1 down
      oFullCount          => oFullCount);          -- out unsigned(kFifoCountWidth-1 down

  -----------------------------------------------------------------------------
  -- Instantiate the dual port RAM module
  -----------------------------------------------------------------------------

  --vhook_e DmaPortOutStrmDPRAM
  DmaPortOutStrmDPRAMx: entity work.DmaPortOutStrmDPRAM (rtl)
    generic map (
      kAddressWidth        => kAddressWidth,         -- in  natural := 6
      kSampleSize          => kSampleSize,           -- in  natural := 8
      kNumOfSamplesPerRead => kNumOfSamplesPerRead,  -- in  natural := 1
      kRdPortWidth         => kRdPortWidth,          -- in  natural := 8
      kFifoCountWidth      => kFifoCountWidth)       -- in  natural
    port map (
      aReset        => aReset,         -- in  boolean
      IClk          => IClk,           -- in  std_logic
      iWriteEnables => iWriteEnables,  -- in  NiDmaByteEnable_t
      iAddr         => iAddr,          -- in  unsigned(kAddressWidth-1 downto 0)
      iDataIn       => iDataIn,        -- in  NiDmaData_t
      OClk          => OClk,           -- in  std_logic
      oReset        => oReset,         -- in  boolean
      oAddr         => oAddr,          -- in  unsigned(kFifoCountWidth-1 downto 0)
      oDataOut      => oDataOut);      -- out std_logic_vector(kRdPortWidth-1 downto 0)


end rtl;
