------------------------------------------------------------------------------
--
-- File: DmaPortInterfaceTemplate.vhd
-- Author: Daria Tioc-Deac
-- Original Project: DmaPort Communication Interface
-- Date: 20 December 2011
--
------------------------------------------------------------------------------
-- (c) 2010 Copyright National Instruments Corporation
-- All Rights Reserved
-- National Instruments Internal Information
------------------------------------------------------------------------------
--
-- Purpose: This file is dynamically generated by the LabVIEW FPGA code
--          generation software. It is instantiated inside rvi_foo, and it
--          provides bus access interface to components in the VI by:
--          - providing register port for PIO accesses to VI and IP
--            components.
--          - providing Irq ports for VI virtual interrupts and IP interrupts.
--          - providing DMA ports for VI and IP DMA requesters.
--
--          This file also instantiates IRQ module and DMA FIFOs, and
--          interfaces with the communication interface module in the
--          toplevel.
------------------------------------------------------------------------------

library ieee;
  use ieee.std_logic_1164.all;

library work;
  use work.PkgNiUtilities.all;
  use work.PkgDmaPortCommunicationInterface.all;
  use work.PkgCommunicationInterface.all;
  use work.PkgCommIntConfiguration.all;
  use work.PkgDmaPortDmaFifos.all;
  use work.PkgDmaPortDmaFifosFlatTypes.all;
  use work.PkgDmaPortCommIfcStreamStates.all;
  use work.PkgDmaPortCommIfcMasterPort.all;
  use work.PkgDmaPortCommIfcMasterPortFlatTypes.all;

entity Interface is
  -------------------------------------------
  -- Dynamically generated generics and ports
  -- BEGIN
  -------------------------------------------
    generic (
    kMiteIoLikeWidthIn : POSITIVE := 34;
    kMiteIoLikeWidthOut : POSITIVE := 51
  );

  port (
   DmaClk : in std_logic ;
   BusClk : in std_logic ;
   PllClk80 : in std_logic ;
   reset : in std_logic ;
   busClkMiteIoLikeFromReshold : in std_logic_vector(kMiteIoLikeWidthIn-1 downto 0);
   busClkMiteIoLikeToReshold : out std_logic_vector(kMiteIoLikeWidthOut-1 downto 0);
   aBusReset : in std_logic ;
   bIrqToInterface : out std_logic_vector(65 downto 0);
   dInputStreamInterfaceFromFifo : out std_logic_vector(19391 downto 0);
   dInputStreamInterfaceToFifo : in std_logic_vector(3839 downto 0);
   dOutputStreamInterfaceFromFifo : out std_logic_vector(4543 downto 0);
   dOutputStreamInterfaceToFifo : in std_logic_vector(21247 downto 0);
   dNiFpgaMasterReadDataToMaster : in std_logic_vector(19519 downto 0);
   dNiFpgaMasterReadRequestFromMaster : out std_logic_vector(5823 downto 0);
   dNiFpgaMasterReadRequestToMaster : in std_logic_vector(63 downto 0);
   dNiFpgaMasterWriteDataFromMaster : out std_logic_vector(16383 downto 0);
   dNiFpgaMasterWriteDataToMaster : in std_logic_vector(3071 downto 0);
   dNiFpgaMasterWriteRequestFromMaster : out std_logic_vector(5823 downto 0);
   dNiFpgaMasterWriteRequestToMaster : in std_logic_vector(63 downto 0);
   dNiFpgaMasterWriteStatusToMaster : in std_logic_vector(959 downto 0);
   bRegPortIn : in std_logic_vector(50 downto 0);
   bRegPortOut : out std_logic_vector(33 downto 0);
   bBusReset : in std_logic 
  );

  -------------------------------------------
  -- Dynamically generated generics and ports
  -- END
  -------------------------------------------

end entity Interface;

architecture rtl of Interface is

  -- Shared signals between blocks
  signal bRegPortInLoc : RegPortIn_t;
  signal bRegPortOutIrqArray : RegPortOutArray_t(Larger(kNumberOfIrqs,1)-1 downto 0);
  signal bIpIrqToInterface : IrqStatusArray_t(Larger(kNumberOfIrqs,1)-1 downto 0);
  signal bIrqToInterfaceArray : IrqToInterfaceArray_t(Larger(kNumberOfIrqs,1)-1 downto 0);

begin

  -- PioBlk : ----------------------------------------------------------------
  -- This block handles wiring of the RegPort between the communication
  -- interface and all the RegPort requesters.
  ----------------------------------------------------------------------------
  PioBlk : block

    signal bRegPortOutFromVi : RegPortOut_t;
    signal bRegPortOutLoc : RegPortOut_t;

  begin

    -------------------------------------------
    -- Interface to the communication interface
    -------------------------------------------
    bRegPortInLoc <= BuildRegPortIn(bRegPortIn);
    bRegPortOut <= to_StdLogicVector(bRegPortOutLoc);

    -------------------------------------------
    -- Interface to the RegPort requesters
    -------------------------------------------
    BusClkMiteIoLikeToReshold <= bRegPortIn;

    bRegPortOutFromVi <= BuildRegPortOut(BusClkMiteIoLikeFromReshold);

    BuildRegPortOut: process(bRegPortOutIrqArray, bRegPortOutFromVi)
      variable RegPortOutTemp : RegPortOut_t;
    begin

      RegPortOutTemp := bRegPortOutFromVi;

      for i in kNumberOfIrqs-1 downto 0 loop
        RegPortOutTemp.Data := RegPortOutTemp.Data or bRegPortOutIrqArray(i).Data;
        RegPortOutTemp.DataValid := RegPortOutTemp.DataValid or bRegPortOutIrqArray(i).DataValid;
        RegPortOutTemp.Ready := RegPortOutTemp.Ready and bRegPortOutIrqArray(i).Ready;
      end loop;

      bRegPortOutLoc <= RegPortOutTemp;

    end process BuildRegPortOut;

  end block PioBlk;

  -- DmaBlk : ----------------------------------------------------------------
  -- This block instantiates DMA FIFOs and hooks up the diagram components and
  -- the stream controller to the DMA FIFOs.
  
  -- Harmish: 08/06/2014: Added support for Flush method
  -- + DmaFlushEnableIn/Out/ClearArray signals create the enable chain.
  -- + Connection to this signals are dynamically done through Interface Emit code.
  --   \\lvfpga\fpga\main\trunk\8.0\source\LabVIEW\resource\RVI\CommunicationInterface\PlugIns\Common\niFpgaWireDmaPortArraysCore.vi
  ----------------------------------------------------------------------------
  DmaBlk : block

    signal DmaClkArray              : DmaClkArray_t;
    signal DmaRwFlagArray           : DmaEnableArray_t;
    signal DmaRwDataInArray         : DmaDataArray_t;
    signal DmaRwDataOutArray        : DmaDataArray_t;
    signal DmaRwTimeoutArray        : DmaTimeoutArray_t;
    signal DmaRwEnableInArray       : DmaEnableArray_t;
    signal DmaRwEnableOutArray      : DmaEnableArray_t;
    signal DmaRwEnableOutClearArray : DmaEnableArray_t;
    signal DmaRwHandshakingInArray  : DmaHandshakingArray_t;
    signal DmaRwHandshakingOutArray : DmaHandshakingArray_t;
    signal DmaFlushEnableInArray    : DmaEnableArray_t;                  
    signal DmaFlushEnableClearArray : DmaEnableArray_t;    
    signal DmaFlushEnableOutArray   : DmaEnableArray_t;            
    signal DmaCtEnableInArray       : DmaEnableArray_t;
    signal DmaCtEnableOutArray      : DmaEnableArray_t;
    signal DmaCtEnableOutClearArray : DmaEnableArray_t;
    signal DmaCtCountArray          : DmaCountArray_t;
    signal DmaStreamStateEnableInArray : DmaEnableArray_t;
    signal DmaStreamStateEnableOutArray : DmaEnableArray_t;
    signal DmaStreamStateEnableClearArray : DmaEnableArray_t;
    signal DmaStreamStateOutArray : StreamStateValueArray_t(kNumberOfDmaChannels-1 downto 0);
    signal dStreamStateEnableInArray : DmaEnableArray_t;
    signal dStreamStateEnableOutArray : DmaEnableArray_t;
    signal dStreamStateEnableClearArray : DmaEnableArray_t;
    signal dStreamStateOutArray : StreamStateValueArray_t(kNumberOfDmaChannels-1 downto 0);
    signal dCurrentStreamStateArray : StreamStateValueArray_t(kNumberOfDmaChannels-1 downto 0);
    signal dStartRequestEnableInArray : DmaEnableArray_t;
    signal dStartRequestEnableOutArray : DmaEnableArray_t;
    signal dStartRequestEnableClearArray : DmaEnableArray_t;
    signal dStopRequestEnableInArray : DmaEnableArray_t;
    signal dStopRequestEnableOutArray : DmaEnableArray_t;
    signal dStopRequestEnableClearArray : DmaEnableArray_t;
    signal dStopWithFlushRequestEnableInArray : DmaEnableArray_t;
    signal dStopWithFlushRequestEnableOutArray : DmaEnableArray_t;
    signal dStopWithFlushRequestEnableClearArray : DmaEnableArray_t;
    signal dStopWithFlushRequestTimeoutArray : DmaTimeoutArray_t;
    signal dStopWithFlushRequestTimedOutArray : DmaFlagArray_t;

    signal dInputStreamInterfaceFromFifoArray:
      InputStreamInterfaceFromFifoArray_t(kNumberOfDmaChannels-1 downto 0);
    signal dInputStreamInterfaceToFifoArray:
      InputStreamInterfaceToFifoArray_t(kNumberOfDmaChannels-1 downto 0);
    signal dOutputStreamInterfaceFromFifoArray:
      OutputStreamInterfaceFromFifoArray_t(kNumberOfDmaChannels-1 downto 0);
    signal dOutputStreamInterfaceToFifoArray:
      OutputStreamInterfaceToFifoArray_t(kNumberOfDmaChannels-1 downto 0);

  begin

    -------------------------------------------
    -- Dynamically generated connections
    -- between DMA requesters and the DMA FIFOs
    -- BEGIN
    -------------------------------------------
    

    -------------------------------------------
    -- Dynamically generated connections
    -- between DMA requesters and the DMA FIFOs
    -- END
    -------------------------------------------
    -------------------------------------------
    -- From stream controllers to DMA FIFOs
    -------------------------------------------
    dInputStreamInterfaceToFifoArray <= UnflattenStreamInterface
                                              (dInputStreamInterfaceToFifo);
    dOutputStreamInterfaceToFifoArray <= UnflattenStreamInterface
                                              (dOutputStreamInterfaceToFifo);

    DmaPortCommIfcFifosx: entity work.DmaPortCommIfcFifos (struct)
      port map (
        aDiagramReset                         => to_Boolean(reset),
        aBusReset                             => to_boolean(aBusReset),
        BusClk                                => DmaClk,
        DefaultClk                            => PllClk80,
        DmaClkArray                           => DmaClkArray,
        DmaFlagArray                          => DmaRwFlagArray,
        DmaDataInArray                        => DmaRwDataInArray,
        DmaDataOutArray                       => DmaRwDataOutArray,
        DmaTimeoutArray                       => DmaRwTimeoutArray,
        DmaEnableInArray                      => DmaRwEnableInArray,
        DmaEnableClearArray                   => DmaRwEnableOutClearArray,
        DmaEnableOutArray                     => DmaRwEnableOutArray,
        DmaHandshakingInArray                 => DmaRwHandshakingInArray,
        DmaHandshakingOutArray                => DmaRwHandshakingOutArray,
        DmaFlushEnableInArray                 => DmaFlushEnableInArray,                
        DmaFlushEnableClearArray              => DmaFlushEnableClearArray, 
        DmaFlushEnableOutArray                => DmaFlushEnableOutArray,            
        DmaCtCountArray                       => DmaCtCountArray,
        DmaCtEnableInArray                    => DmaCtEnableInArray,
        DmaCtEnableOutClearArray              => DmaCtEnableOutClearArray,
        DmaCtEnableOutArray                   => DmaCtEnableOutArray,
        DmaStreamStateEnableInArray           => DmaStreamStateEnableInArray,
        DmaStreamStateEnableOutArray          => DmaStreamStateEnableOutArray,
        DmaStreamStateEnableClearArray        => DmaStreamStateEnableClearArray,
        DmaStreamStateOutArray                => DmaStreamStateOutArray,
        dStreamStateEnableInArray             => dStreamStateEnableInArray,
        dStreamStateEnableOutArray            => dStreamStateEnableOutArray,
        dStreamStateEnableClearArray          => dStreamStateEnableClearArray,
        dStreamStateOutArray                  => dStreamStateOutArray,
        dCurrentStreamStateArray              => dCurrentStreamStateArray,
        dStartRequestEnableInArray            => dStartRequestEnableInArray,
        dStartRequestEnableOutArray           => dStartRequestEnableOutArray,
        dStartRequestEnableClearArray         => dStartRequestEnableClearArray,
        dStopRequestEnableInArray             => dStopRequestEnableInArray,
        dStopRequestEnableOutArray            => dStopRequestEnableOutArray,
        dStopRequestEnableClearArray          => dStopRequestEnableClearArray,
        dStopWithFlushRequestEnableInArray    => dStopWithFlushRequestEnableInArray,
        dStopWithFlushRequestEnableOutArray   => dStopWithFlushRequestEnableOutArray,
        dStopWithFlushRequestEnableClearArray => dStopWithFlushRequestEnableClearArray,
        dStopWithFlushRequestTimeoutArray     => dStopWithFlushRequestTimeoutArray,
        dStopWithFlushRequestTimedOutArray    => dStopWithFlushRequestTimedOutArray,
        bInputStreamInterfaceToFifo           => dInputStreamInterfaceToFifoArray,
        bInputStreamInterfaceFromFifo         => dInputStreamInterfaceFromFifoArray,
        bOutputStreamInterfaceToFifo          => dOutputStreamInterfaceToFifoArray,
        bOutputStreamInterfaceFromFifo        => dOutputStreamInterfaceFromFifoArray);

    -------------------------------------------
    -- From DMA FIFOs to stream controllers
    -------------------------------------------
    dInputStreamInterfaceFromFifo <= FlattenStreamInterface
                                       (dInputStreamInterfaceFromFifoArray);
    dOutputStreamInterfaceFromFifo <= FlattenStreamInterface
                                      (dOutputStreamInterfaceFromFifoArray);
  end block DmaBlk;

  
  -- MasterPortBlk : ---------------------------------------------------------
  -- This block hooks up the MasterPort requesters to the communication
  -- interface MasterPort signals
  ----------------------------------------------------------------------------
  MasterPortBlk : block

    signal dNiFpgaMasterWriteRequestFromMasterArray:
      NiFpgaMasterWriteRequestFromMasterArray_t(kNumberOfMasterPorts-1 downto 0);
    signal dNiFpgaMasterWriteRequestToMasterArray:
      NiFpgaMasterWriteRequestToMasterArray_t(kNumberOfMasterPorts-1 downto 0);
    signal dNiFpgaMasterWriteDataFromMasterArray:
      NiFpgaMasterWriteDataFromMasterArray_t(kNumberOfMasterPorts-1 downto 0);
    signal dNiFpgaMasterWriteDataToMasterArray:
      NiFpgaMasterWriteDataToMasterArray_t(kNumberOfMasterPorts-1 downto 0);
    signal dNiFpgaMasterWriteStatusToMasterArray:
      NiFpgaMasterWriteStatusToMasterArray_t(kNumberOfMasterPorts-1 downto 0);
    signal dNiFpgaMasterReadRequestFromMasterArray:
      NiFpgaMasterReadRequestFromMasterArray_t(kNumberOfMasterPorts-1 downto 0);
    signal dNiFpgaMasterReadRequestToMasterArray:
      NiFpgaMasterReadRequestToMasterArray_t(kNumberOfMasterPorts-1 downto 0);
    signal dNiFpgaMasterReadDataToMasterArray:
      NiFpgaMasterReadDataToMasterArray_t(kNumberOfMasterPorts-1 downto 0);

  begin

    dNiFpgaMasterWriteRequestToMasterArray    <=
          UnflattenMasterPortInterface(MasterPortInterfaceVectorToArray(
            ArraySize => dNiFpgaMasterWriteRequestToMasterArray'length,
            Vector => dNiFpgaMasterWriteRequestToMaster));
    dNiFpgaMasterWriteDataToMasterArray       <=
          UnflattenMasterPortInterface(MasterPortInterfaceVectorToArray(
            ArraySize => dNiFpgaMasterWriteDataToMasterArray'length,
            Vector => dNiFpgaMasterWriteDataToMaster));
    dNiFpgaMasterWriteStatusToMasterArray     <=
          UnflattenMasterPortInterface(MasterPortInterfaceVectorToArray(
            ArraySize => dNiFpgaMasterWriteStatusToMasterArray'length,
            Vector => dNiFpgaMasterWriteStatusToMaster));
    dNiFpgaMasterReadRequestToMasterArray     <=
          UnflattenMasterPortInterface(MasterPortInterfaceVectorToArray(
            ArraySize => dNiFpgaMasterReadRequestToMasterArray'length,
            Vector => dNiFpgaMasterReadRequestToMaster));
    dNiFpgaMasterReadDataToMasterArray        <=
          UnflattenMasterPortInterface(MasterPortInterfaceVectorToArray(
            ArraySize => dNiFpgaMasterReadDataToMasterArray'length,
            Vector => dNiFpgaMasterReadDataToMaster));
            
    -------------------------------------------
    -- Dynamically generated connections
    -- between MasterPort requesters and 
    -- MasterPorts
    -- BEGIN
    -------------------------------------------                                              
        dNiFpgaMasterWriteRequestFromMasterArray(0) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(0)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(0)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(1) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(1)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(1)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(2) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(2)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(2)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(3) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(3)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(3)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(4) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(4)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(4)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(5) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(5)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(5)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(6) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(6)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(6)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(7) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(7)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(7)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(8) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(8)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(8)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(9) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(9)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(9)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(10) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(10)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(10)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(11) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(11)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(11)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(12) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(12)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(12)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(13) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(13)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(13)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(14) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(14)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(14)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(15) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(15)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(15)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(16) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(16)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(16)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(17) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(17)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(17)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(18) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(18)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(18)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(19) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(19)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(19)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(20) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(20)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(20)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(21) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(21)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(21)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(22) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(22)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(22)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(23) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(23)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(23)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(24) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(24)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(24)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(25) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(25)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(25)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(26) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(26)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(26)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(27) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(27)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(27)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(28) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(28)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(28)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(29) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(29)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(29)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(30) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(30)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(30)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(31) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(31)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(31)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(32) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(32)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(32)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(33) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(33)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(33)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(34) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(34)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(34)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(35) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(35)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(35)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(36) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(36)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(36)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(37) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(37)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(37)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(38) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(38)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(38)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(39) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(39)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(39)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(40) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(40)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(40)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(41) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(41)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(41)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(42) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(42)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(42)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(43) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(43)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(43)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(44) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(44)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(44)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(45) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(45)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(45)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(46) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(46)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(46)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(47) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(47)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(47)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(48) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(48)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(48)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(49) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(49)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(49)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(50) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(50)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(50)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(51) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(51)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(51)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(52) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(52)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(52)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(53) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(53)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(53)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(54) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(54)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(54)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(55) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(55)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(55)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(56) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(56)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(56)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(57) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(57)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(57)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(58) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(58)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(58)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(59) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(59)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(59)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(60) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(60)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(60)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(61) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(61)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(61)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(62) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(62)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(62)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;
    dNiFpgaMasterWriteRequestFromMasterArray(63) <= 
          kNiFpgaMasterWriteRequestFromMasterZero;
    dNiFpgaMasterWriteDataFromMasterArray(63)    <= 
         kNiFpgaMasterWriteDataFromMasterZero;
    dNiFpgaMasterReadRequestFromMasterArray(63)  <= 
          kNiFpgaMasterReadRequestFromMasterZero;

    -------------------------------------------
    -- Dynamically generated connections
    -- between MasterPort requesters and 
    -- MasterPorts
    -- END
    -------------------------------------------
    
    dNiFpgaMasterWriteRequestFromMaster <= 
          FlattenMasterPortInterface(dNiFpgaMasterWriteRequestFromMasterArray);
    dNiFpgaMasterWriteDataFromMaster    <= 
          FlattenMasterPortInterface(dNiFpgaMasterWriteDataFromMasterArray);
    dNiFpgaMasterReadRequestFromMaster  <= 
          FlattenMasterPortInterface(dNiFpgaMasterReadRequestFromMasterArray);
    
  end block MasterPortBlk;

  -- IrqBlk : ----------------------------------------------------------------
  -- This block instantiates IRQ logic and hooks up the IRQ requesters and
  -- the communication interface to the IRQ logic.
  ----------------------------------------------------------------------------
  IrqBlk : block

    signal IrqClkArray          : IrqClkArray_t;
    signal iIrqInArray          : IrqInArray_t;
    signal iIrqOutArray         : IrqOutArray_t;
    signal iIrqStatusInArray    : IrqStatusInArray_t;
    signal iIrqStatusOutArray   : IrqStatusOutArray_t;
    signal bIpIrq               : std_logic;

  begin

    GenerateIrqComponent : for i in 0 to kNumberOfIrqs-1 generate

      -- Tie the IP IRQ to the status line.  We are not currently supporting clear
      -- functionality.
      
      -- When Clear functionality will be implemented, must be checked if it's
      -- safe to pass this vector to a double sync (CAR #434493)
      
      bIpIrqToInterface(i).Status <= bIpIrq;
      bIpIrqToInterface(i).Clear <= '0';

      ----------------------------------------------
      -- Dynamically generated connections
      -- between IRQ requesters and the IRQ module.
      -- BEGIN
      ----------------------------------------------
        -- Wiring the Irq ports
  -- FPGA VI Interrupt Ports
  IrqClkArray(0) <= BusClk;
  iIrqOutArray(0).EnableClear <= '0';
  iIrqOutArray(0).EnableIn <= '0';
  iIrqStatusOutArray(0).EnableClear <= '0';
  iIrqStatusOutArray(0).EnableIn <= '0';
  -- IP Interrupt Port
  bIpIrq <= '0';


      ----------------------------------------------
      -- Dynamically generated connections
      -- between IRQ requesters and the IRQ module.
      -- END
      ----------------------------------------------

      DmaPortCommIfcLvFpgaIrqx: entity work.DmaPortCommIfcLvFpgaIrq (rtl)
        port map (
          aDiagramReset     => to_Boolean(reset),
          aBusReset         => to_Boolean(aBusReset),
          BusClk            => BusClk,
          bReset            => false,
          IrqClk            => IrqClkArray(i),
          iIrqEnableIn      => iIrqOutArray(i).EnableIn,
          iIrqEnableOut     => iIrqInArray(i).EnableOut,
          iIrqEnableClear   => iIrqOutArray(i).EnableClear,
          iIrqNum           => iIrqOutArray(i).IrqNum,
          iIrqAckStatus           => iIrqStatusInArray(i).Status,
          iIrqAckStatusEnableIn   => iIrqStatusOutArray(i).EnableIn,
          iIrqAckStatusEnableOut  => iIrqStatusInArray(i).EnableOut,
          iIrqAckStatusEnableClear => iIrqStatusOutArray(i).EnableClear,
          bIpIrqToInterface   => bIpIrqToInterface(i),
          bRegPortIn        => bRegPortInLoc,
          bRegPortOut       => bRegPortOutIrqArray(i),
          bIrqToInterface   => bIrqToInterfaceArray(i));

    end generate GenerateIrqComponent;

    bIrqToInterface <= to_StdLogicVector(bIrqToInterfaceArray);

  end block IrqBlk;

end architecture rtl;
