-------------------------------------------------------------------------------
--
-- File: PkgNiDmaRegMap.vhd
-- Author: Autogenerated by XmlParse
-- Original Project: --
-- Date: --
--
-------------------------------------------------------------------------------
-- (c) 2015 Copyright National Instruments Corporation
-- All Rights Reserved
-- National Instruments Internal Information
-------------------------------------------------------------------------------
--
-- Purpose:
--   The constants in this file are autogenerated by XmlParse and should
-- be used by testbench code to access specific register fields.
--
-------------------------------------------------------------------------------

library ieee;
  use ieee.std_logic_1164.all;

package PkgNiDmaRegMap is

--===============================================================================
-- A numerically ordered list of registers and their VHDL source files
--===============================================================================

  -- ChannelBaseAddress                : 0x10 (NiDmaRegisterBlock.vhd)
  -- ChannelBaseSize                   : 0x18 (NiDmaRegisterBlock.vhd)
  -- ChannelNextListLinkAddress        : 0x20 (NiDmaRegisterBlock.vhd)
  -- ChannelNextListLinkSize           : 0x34 (NiDmaRegisterBlock.vhd)
  -- ChannelMemoryAddress              : 0x38 (NiDmaRegisterBlock.vhd)
  -- ChannelBaggage                    : 0x40 (NiDmaRegisterBlock.vhd)
  -- ChannelLinkAddress                : 0x48 (NiDmaRegisterBlock.vhd)
  -- ChannelLinkSize                   : 0x50 (NiDmaRegisterBlock.vhd)
  -- ChannelControl                    : 0x54 (NiDmaRegisterBlock.vhd)
  -- ChannelOperation                  : 0x58 (NiDmaRegisterBlock.vhd)
  -- ChannelStatus                     : 0x60 (NiDmaRegisterBlock.vhd)
  -- ChannelVolatileStatus             : 0x68 (NiDmaRegisterBlock.vhd)
  -- ChannelMemorySize                 : 0x70 (NiDmaRegisterBlock.vhd)
  -- ChannelTotalTransferCountCompare  : 0x90 (NiDmaRegisterBlock.vhd)
  -- ChannelTotalTransferCountStatus   : 0xA0 (NiDmaRegisterBlock.vhd)
  -- ChannelTotalTransferCountLatching : 0xA8 (NiDmaRegisterBlock.vhd)
  -- ChannelDoNotAccess                : 0xFC (NiDmaRegisterBlock.vhd)



--===============================================================================
-- RegTypes
--===============================================================================

--===============================================================================
-- Register Group NiDmaRegisters
--===============================================================================

  -- Enumerated type ByteSwap_t
  constant kByteSwap_tSize : integer := 4;
  constant kSwapNoneOr8bitData  : integer := 0;  -- ByteSwap_t:SwapNoneOr8bitData
  constant kSwap16bitData       : integer := 1;  -- ByteSwap_t:Swap16bitData
  constant kSwap32bitData       : integer := 2;  -- ByteSwap_t:Swap32bitData
  constant kSwap64bitData       : integer := 3;  -- ByteSwap_t:Swap64bitData

  -- Enumerated type DmaMode_t
  constant kDmaMode_tSize : integer := 3;
  constant kModeNull          : integer := 0;  -- DmaMode_t:ModeNull
  constant kModeNormal        : integer := 1;  -- DmaMode_t:ModeNormal
  constant kModeLinkChaining  : integer := 2;  -- DmaMode_t:ModeLinkChaining

  -- Enumerated type Size_t
  constant kSize_tSize : integer := 4;
  constant k8bit   : integer := 0;  -- Size_t:8bit
  constant k16bit  : integer := 1;  -- Size_t:16bit
  constant k32bit  : integer := 2;  -- Size_t:32bit
  constant k64bit  : integer := 3;  -- Size_t:64bit

  -- ChannelBaseAddress Register (from NiDmaRegisterBlock.vhd)
  constant kChannelBaseAddress : integer := 16#10#; -- Register Offset
  constant kChannelBaseAddressSize: integer := 64;
  constant kChannelBaseAddressMask : std_logic_vector(63 downto 0) := X"ffffffffffffffff";
  constant kBaseAddressSize : integer := 64;  --ChannelBaseAddress:BaseAddress
  constant kBaseAddressMsb  : integer := 63;  --ChannelBaseAddress:BaseAddress
  constant kBaseAddress     : integer :=  0;  --ChannelBaseAddress:BaseAddress

  -- ChannelBaseSize Register (from NiDmaRegisterBlock.vhd)
  constant kChannelBaseSize : integer := 16#18#; -- Register Offset
  constant kChannelBaseSizeSize: integer := 64;
  constant kChannelBaseSizeMask : std_logic_vector(63 downto 0) := X"ffffffffffffffff";
  constant kBaseSizeSize : integer := 64;  --ChannelBaseSize:BaseSize
  constant kBaseSizeMsb  : integer := 63;  --ChannelBaseSize:BaseSize
  constant kBaseSize     : integer :=  0;  --ChannelBaseSize:BaseSize

  -- ChannelNextListLinkAddress Register (from NiDmaRegisterBlock.vhd)
  constant kChannelNextListLinkAddress : integer := 16#20#; -- Register Offset
  constant kChannelNextListLinkAddressSize: integer := 64;
  constant kChannelNextListLinkAddressMask : std_logic_vector(63 downto 0) := X"ffffffffffffffff";
  constant kDoorbellAddressSize : integer := 64;  --ChannelNextListLinkAddress:DoorbellAddress
  constant kDoorbellAddressMsb  : integer := 63;  --ChannelNextListLinkAddress:DoorbellAddress
  constant kDoorbellAddress     : integer :=  0;  --ChannelNextListLinkAddress:DoorbellAddress

  -- ChannelNextListLinkSize Register (from NiDmaRegisterBlock.vhd)
  constant kChannelNextListLinkSize : integer := 16#34#; -- Register Offset
  constant kChannelNextListLinkSizeSize: integer := 32;
  constant kChannelNextListLinkSizeMask : std_logic_vector(31 downto 0) := X"ffffffff";
  constant kDoorbellValueSize : integer := 32;  --ChannelNextListLinkSize:DoorbellValue
  constant kDoorbellValueMsb  : integer := 31;  --ChannelNextListLinkSize:DoorbellValue
  constant kDoorbellValue     : integer :=  0;  --ChannelNextListLinkSize:DoorbellValue

  -- ChannelMemoryAddress Register (from NiDmaRegisterBlock.vhd)
  constant kChannelMemoryAddress : integer := 16#38#; -- Register Offset
  constant kChannelMemoryAddressSize: integer := 64;
  constant kChannelMemoryAddressMask : std_logic_vector(63 downto 0) := X"ffffffffffffffff";
  constant kMemoryAddressSize : integer := 64;  --ChannelMemoryAddress:MemoryAddress
  constant kMemoryAddressMsb  : integer := 63;  --ChannelMemoryAddress:MemoryAddress
  constant kMemoryAddress     : integer :=  0;  --ChannelMemoryAddress:MemoryAddress

  -- ChannelBaggage Register (from NiDmaRegisterBlock.vhd)
  constant kChannelBaggage : integer := 16#40#; -- Register Offset
  constant kChannelBaggageSize: integer := 64;
  constant kChannelBaggageMask : std_logic_vector(63 downto 0) := X"ffffffffffffffff";
  constant kBaggageSize : integer := 64;  --ChannelBaggage:Baggage
  constant kBaggageMsb  : integer := 63;  --ChannelBaggage:Baggage
  constant kBaggage     : integer :=  0;  --ChannelBaggage:Baggage

  -- ChannelLinkAddress Register (from NiDmaRegisterBlock.vhd)
  constant kChannelLinkAddress : integer := 16#48#; -- Register Offset
  constant kChannelLinkAddressSize: integer := 64;
  constant kChannelLinkAddressMask : std_logic_vector(63 downto 0) := X"ffffffffffffffff";
  constant kLinkAddressSize : integer := 64;  --ChannelLinkAddress:LinkAddress
  constant kLinkAddressMsb  : integer := 63;  --ChannelLinkAddress:LinkAddress
  constant kLinkAddress     : integer :=  0;  --ChannelLinkAddress:LinkAddress

  -- ChannelLinkSize Register (from NiDmaRegisterBlock.vhd)
  constant kChannelLinkSize : integer := 16#50#; -- Register Offset
  constant kChannelLinkSizeSize: integer := 32;
  constant kChannelLinkSizeMask : std_logic_vector(31 downto 0) := X"ffffffff";
  constant kLinkSizeSize : integer := 32;  --ChannelLinkSize:LinkSize
  constant kLinkSizeMsb  : integer := 31;  --ChannelLinkSize:LinkSize
  constant kLinkSize     : integer :=  0;  --ChannelLinkSize:LinkSize

  -- ChannelControl Register (from NiDmaRegisterBlock.vhd)
  constant kChannelControl : integer := 16#54#; -- Register Offset
  constant kChannelControlSize: integer := 32;
  constant kChannelControlMask : std_logic_vector(31 downto 0) := X"0ab08307";
  constant kModeSize : integer := 2;  --ChannelControl:Mode
  constant kModeMsb  : integer := 1;  --ChannelControl:Mode
  constant kMode     : integer := 0;  --ChannelControl:Mode
  constant kDisableLinkFetchingSize : integer := 1;  --ChannelControl:DisableLinkFetching
  constant kDisableLinkFetchingMsb  : integer := 2;  --ChannelControl:DisableLinkFetching
  constant kDisableLinkFetching     : integer := 2;  --ChannelControl:DisableLinkFetching
  constant kByteSwapSize : integer := 2;  --ChannelControl:ByteSwap
  constant kByteSwapMsb  : integer := 9;  --ChannelControl:ByteSwap
  constant kByteSwap     : integer := 8;  --ChannelControl:ByteSwap
  constant kNotifyOnDoneSize : integer :=  1;  --ChannelControl:NotifyOnDone
  constant kNotifyOnDoneMsb  : integer := 15;  --ChannelControl:NotifyOnDone
  constant kNotifyOnDone     : integer := 15;  --ChannelControl:NotifyOnDone
  constant kDoorbellSizeSize : integer :=  2;  --ChannelControl:DoorbellSize
  constant kDoorbellSizeMsb  : integer := 21;  --ChannelControl:DoorbellSize
  constant kDoorbellSize     : integer := 20;  --ChannelControl:DoorbellSize
  constant kPushOnDoneSize : integer :=  1;  --ChannelControl:PushOnDone
  constant kPushOnDoneMsb  : integer := 23;  --ChannelControl:PushOnDone
  constant kPushOnDone     : integer := 23;  --ChannelControl:PushOnDone
  constant kNotifyOnTotalCountSize : integer :=  1;  --ChannelControl:NotifyOnTotalCount
  constant kNotifyOnTotalCountMsb  : integer := 25;  --ChannelControl:NotifyOnTotalCount
  constant kNotifyOnTotalCount     : integer := 25;  --ChannelControl:NotifyOnTotalCount
  constant kNotifyOnErrorSize : integer :=  1;  --ChannelControl:NotifyOnError
  constant kNotifyOnErrorMsb  : integer := 27;  --ChannelControl:NotifyOnError
  constant kNotifyOnError     : integer := 27;  --ChannelControl:NotifyOnError

  -- ChannelOperation Register (from NiDmaRegisterBlock.vhd)
  constant kChannelOperation : integer := 16#58#; -- Register Offset
  constant kChannelOperationSize: integer := 32;
  constant kChannelOperationMask : std_logic_vector(31 downto 0) := X"02000017";
  constant kStartSize : integer := 1;  --ChannelOperation:Start
  constant kStartMsb  : integer := 0;  --ChannelOperation:Start
  constant kStart     : integer := 0;  --ChannelOperation:Start
  constant kStopSize : integer := 1;  --ChannelOperation:Stop
  constant kStopMsb  : integer := 1;  --ChannelOperation:Stop
  constant kStop     : integer := 1;  --ChannelOperation:Stop
  constant kClrTtcSize : integer := 1;  --ChannelOperation:ClrTtc
  constant kClrTtcMsb  : integer := 2;  --ChannelOperation:ClrTtc
  constant kClrTtc     : integer := 2;  --ChannelOperation:ClrTtc
  constant kBaseRegsReadySize : integer := 1;  --ChannelOperation:BaseRegsReady
  constant kBaseRegsReadyMsb  : integer := 4;  --ChannelOperation:BaseRegsReady
  constant kBaseRegsReady     : integer := 4;  --ChannelOperation:BaseRegsReady
  constant kArmTotalCountInterruptSize : integer :=  1;  --ChannelOperation:ArmTotalCountInterrupt
  constant kArmTotalCountInterruptMsb  : integer := 25;  --ChannelOperation:ArmTotalCountInterrupt
  constant kArmTotalCountInterrupt     : integer := 25;  --ChannelOperation:ArmTotalCountInterrupt

  -- ChannelStatus Register (from NiDmaRegisterBlock.vhd)
  constant kChannelStatus : integer := 16#60#; -- Register Offset
  constant kChannelStatusSize: integer := 32;
  constant kChannelStatusMask : std_logic_vector(31 downto 0) := X"be00cfff";
  constant kStreamSize : integer := 12;  --ChannelStatus:Stream
  constant kStreamMsb  : integer := 11;  --ChannelStatus:Stream
  constant kStream     : integer :=  0;  --ChannelStatus:Stream
  constant kLinkReadyBarInvalidSize : integer :=  1;  --ChannelStatus:LinkReadyBarInvalid
  constant kLinkReadyBarInvalidMsb  : integer := 14;  --ChannelStatus:LinkReadyBarInvalid
  constant kLinkReadyBarInvalid     : integer := 14;  --ChannelStatus:LinkReadyBarInvalid
  constant kDoneSize : integer :=  1;  --ChannelStatus:Done
  constant kDoneMsb  : integer := 15;  --ChannelStatus:Done
  constant kDone     : integer := 15;  --ChannelStatus:Done
  constant kTotalCountSize : integer :=  1;  --ChannelStatus:TotalCount
  constant kTotalCountMsb  : integer := 25;  --ChannelStatus:TotalCount
  constant kTotalCount     : integer := 25;  --ChannelStatus:TotalCount
  constant kLastLinkSize : integer :=  1;  --ChannelStatus:LastLink
  constant kLastLinkMsb  : integer := 26;  --ChannelStatus:LastLink
  constant kLastLink     : integer := 26;  --ChannelStatus:LastLink
  constant kErrorSize : integer :=  1;  --ChannelStatus:Error
  constant kErrorMsb  : integer := 27;  --ChannelStatus:Error
  constant kError     : integer := 27;  --ChannelStatus:Error
  constant kInterruptSourceSize : integer :=  2;  --ChannelStatus:InterruptSource
  constant kInterruptSourceMsb  : integer := 29;  --ChannelStatus:InterruptSource
  constant kInterruptSource     : integer := 28;  --ChannelStatus:InterruptSource
  constant kInterruptPendingSize : integer :=  1;  --ChannelStatus:InterruptPending
  constant kInterruptPendingMsb  : integer := 31;  --ChannelStatus:InterruptPending
  constant kInterruptPending     : integer := 31;  --ChannelStatus:InterruptPending

  -- ChannelVolatileStatus Register (from NiDmaRegisterBlock.vhd)
  constant kChannelVolatileStatus : integer := 16#68#; -- Register Offset
  constant kChannelVolatileStatusSize: integer := 32;
  constant kChannelVolatileStatusMask : std_logic_vector(31 downto 0) := X"00000000";

  -- ChannelMemorySize Register (from NiDmaRegisterBlock.vhd)
  constant kChannelMemorySize : integer := 16#70#; -- Register Offset
  constant kChannelMemorySizeSize: integer := 64;
  constant kChannelMemorySizeMask : std_logic_vector(63 downto 0) := X"ffffffffffffffff";
  constant kMemorySizeSize : integer := 64;  --ChannelMemorySize:MemorySize
  constant kMemorySizeMsb  : integer := 63;  --ChannelMemorySize:MemorySize
  constant kMemorySize     : integer :=  0;  --ChannelMemorySize:MemorySize

  -- ChannelTotalTransferCountCompare Register (from NiDmaRegisterBlock.vhd)
  constant kChannelTotalTransferCountCompare : integer := 16#90#; -- Register Offset
  constant kChannelTotalTransferCountCompareSize: integer := 64;
  constant kChannelTotalTransferCountCompareMask : std_logic_vector(63 downto 0) := X"ffffffffffffffff";
  constant kTotalCompareCountSize : integer := 64;  --ChannelTotalTransferCountCompare:TotalCompareCount
  constant kTotalCompareCountMsb  : integer := 63;  --ChannelTotalTransferCountCompare:TotalCompareCount
  constant kTotalCompareCount     : integer :=  0;  --ChannelTotalTransferCountCompare:TotalCompareCount

  -- ChannelTotalTransferCountStatus Register (from NiDmaRegisterBlock.vhd)
  constant kChannelTotalTransferCountStatus : integer := 16#A0#; -- Register Offset
  constant kChannelTotalTransferCountStatusSize: integer := 64;
  constant kChannelTotalTransferCountStatusMask : std_logic_vector(63 downto 0) := X"ffffffffffffffff";
  constant kTotalTransferCountStatusSize : integer := 64;  --ChannelTotalTransferCountStatus:TotalTransferCountStatus
  constant kTotalTransferCountStatusMsb  : integer := 63;  --ChannelTotalTransferCountStatus:TotalTransferCountStatus
  constant kTotalTransferCountStatus     : integer :=  0;  --ChannelTotalTransferCountStatus:TotalTransferCountStatus

  -- ChannelTotalTransferCountLatching Register (from NiDmaRegisterBlock.vhd)
  constant kChannelTotalTransferCountLatching : integer := 16#A8#; -- Register Offset
  constant kChannelTotalTransferCountLatchingSize: integer := 64;
  constant kChannelTotalTransferCountLatchingMask : std_logic_vector(63 downto 0) := X"ffffffffffffffff";
  constant kTotalTransferCountLatchingSize : integer := 64;  --ChannelTotalTransferCountLatching:TotalTransferCountLatching
  constant kTotalTransferCountLatchingMsb  : integer := 63;  --ChannelTotalTransferCountLatching:TotalTransferCountLatching
  constant kTotalTransferCountLatching     : integer :=  0;  --ChannelTotalTransferCountLatching:TotalTransferCountLatching

  -- ChannelDoNotAccess Register (from NiDmaRegisterBlock.vhd)
  constant kChannelDoNotAccess : integer := 16#FC#; -- Register Offset
  constant kChannelDoNotAccessSize: integer := 32;
  constant kChannelDoNotAccessMask : std_logic_vector(31 downto 0) := X"ffffffff";
  constant kIllegalSize : integer := 32;  --ChannelDoNotAccess:Illegal
  constant kIllegalMsb  : integer := 31;  --ChannelDoNotAccess:Illegal
  constant kIllegal     : integer :=  0;  --ChannelDoNotAccess:Illegal

end package;
