------------------------------------------------------------------------------
--
-- File: DmaPortWindowTemplate.vhd
-- Author: Daria Tioc-Deac
-- Original Project: DmaPort Communication Interface
-- Date: 20 December 2011
--
------------------------------------------------------------------------------
-- (c) 2011 Copyright National Instruments Corporation
-- All Rights Reserved
-- National Instruments Internal Information
------------------------------------------------------------------------------
--
-- Purpose: This is the top most level file that is dynamically generated by
--          LabVIEW FPGA code generation software. It is instantiated by the
--          target provided top level file. The window does the following:
--           - Instantiate rvi_foo : This contains the user diagram logic.
--           - Instantiate DCM/PLL : To generate user derived clocks.
--           - Instantiate CLIP modules.
--           - Connect rvi_foo with the DmaPort communication interface
--             that is instantiated in the target toplevel file.
--
------------------------------------------------------------------------------

library ieee;
  use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

Library work;
use work.PkgNiUtilities.all;
use work.PkgCommIntConfiguration.all;
use work.PkgCommunicationInterface.all;
use work.PkgDmaPortCommunicationInterface.all;
use work.PkgDmaPortDmaFifos.all;
use work.PkgDmaPortDmaFifosFlatTypes.all;
use work.PkgDmaPortCommIfcMasterPort.all;
use work.PkgDmaPortCommIfcMasterPortFlatTypes.all;

--synthesis translate_off
use work.PkgNiFpgaSimulationModelPrivate.all;
--synthesis translate_on

--synthesis translate_off
Library UNISIM;
use UNISIM.vcomponents.all;
--synthesis translate_on

entity TheWindow is
   port(
    -----------------------------------
    -- Communication interface ports
    -----------------------------------
    -- Reset ports
    aBusReset : in boolean;

    -- Register Access/ PIO Ports
    bRegPortIn : in RegPortIn_t;
    bRegPortOut : out RegPortOut_t;
    bRegPortTimeout : in boolean;

    -- DMA Stream Ports
    dInputStreamInterfaceToFifo : in InputStreamInterfaceToFifoArray_t
      (Larger(kNumberOfDmaChannels,1)-1 downto 0);
    dInputStreamInterfaceFromFifo : out InputStreamInterfaceFromFifoArray_t
      (Larger(kNumberOfDmaChannels,1)-1 downto 0);
    dOutputStreamInterfaceToFifo : in OutputStreamInterfaceToFifoArray_t
      (Larger(kNumberOfDmaChannels,1)-1 downto 0);
    dOutputStreamInterfaceFromFifo : out OutputStreamInterfaceFromFifoArray_t
      (Larger(kNumberOfDmaChannels,1)-1 downto 0);

    -- Memory Buffer DMA Stream Ports

    -- IRQ Ports
    bIrqToInterface : out IrqToInterfaceArray_t(Larger(kNumberOfIrqs,1)-1 downto 0);

    -- MasterPort Ports
    dNiFpgaMasterWriteRequestFromMaster : out
      NiFpgaMasterWriteRequestFromMasterArray_t (Larger(kNumberOfMasterPorts,1)-1 downto 0);
    dNiFpgaMasterWriteRequestToMaster : in
      NiFpgaMasterWriteRequestToMasterArray_t(Larger(kNumberOfMasterPorts,1)-1 downto 0);
    dNiFpgaMasterWriteDataFromMaster : out
      NiFpgaMasterWriteDataFromMasterArray_t(Larger(kNumberOfMasterPorts,1)-1 downto 0);
    dNiFpgaMasterWriteDataToMaster : in
      NiFpgaMasterWriteDataToMasterArray_t(Larger(kNumberOfMasterPorts,1)-1 downto 0);
    dNiFpgaMasterWriteStatusToMaster : in
      NiFpgaMasterWriteStatusToMasterArray_t(Larger(kNumberOfMasterPorts,1)-1 downto 0);

    dNiFpgaMasterReadRequestFromMaster : out
      NiFpgaMasterReadRequestFromMasterArray_t(Larger(kNumberOfMasterPorts,1)-1 downto 0);
    dNiFpgaMasterReadRequestToMaster : in
      NiFpgaMasterReadRequestToMasterArray_t(Larger(kNumberOfMasterPorts,1)-1 downto 0);
    dNiFpgaMasterReadDataToMaster : in
      NiFpgaMasterReadDataToMasterArray_t(Larger(kNumberOfMasterPorts,1)-1 downto 0);

    -----------------------------------
    -- Clocks from TopLevel
    -----------------------------------
    DmaClk :  in std_logic;
BusClk :  in std_logic;
ReliableClkIn :  in std_logic;
PllClk80 :  in std_logic;
DlyRefClk :  in std_logic;
PxieClk100 :  in std_logic;
DramClkLvFpga :  in std_logic;
Dram0ClkSocket :  in std_logic;
Dram1ClkSocket :  in std_logic;
Dram0ClkUser :  in std_logic;
Dram1ClkUser :  in std_logic;


    -----------------------------------
    -- Handshaking signals for derived
    -- clocks on external clocks
    -----------------------------------
    

    -----------------------------------
    -- IO Node ports
    -----------------------------------
        pIntSync100 : in std_logic;
    aIntClk10 : in std_logic;
    aDramReady : in std_logic;


    -----------------------------------
    -- Target Method and Properties ports
    -----------------------------------
    bdAxiStreamRdFromClipTData : in  std_logic_vector(31 downto 0);
bdAxiStreamRdFromClipTLast : in std_logic;
bdAxiStreamRdFromClipTValid : in std_logic;
bdAxiStreamRdToClipTReady : out std_logic;
bdAxiStreamWrFromClipTReady : in std_logic;
bdAxiStreamWrToClipTData : out  std_logic_vector(31 downto 0);
bdAxiStreamWrToClipTLast : out std_logic;
bdAxiStreamWrToClipTValid : out std_logic;
bdIFifoRdData : out  std_logic_vector(63 downto 0);
bdIFifoRdDataValid : out std_logic;
bdIFifoRdIsError : out std_logic;
bdIFifoRdReadyForInput : in std_logic;
bdIFifoWrData : in  std_logic_vector(63 downto 0);
bdIFifoWrDataValid : in std_logic;
bdIFifoWrReadyForOutput : out std_logic;


    -----------------------------------
    -- Pass through LabVIEW FPGA ports
    -----------------------------------
    

    -----------------------------------
    -- CLIP Socket ports
    -----------------------------------
        du0DramAddrFifoAddr : out std_logic_vector(28 downto 0);
    du0DramAddrFifoCmd : out std_logic_vector(2 downto 0);
    du0DramAddrFifoFull : in std_logic;
    du0DramAddrFifoWrEn : out std_logic;
    du0DramPhyInitDone : in std_logic;
    du0DramRdDataValid : in std_logic;
    du0DramRdFifoDataOut : in std_logic_vector(255 downto 0);
    du0DramWrFifoDataIn : out std_logic_vector(255 downto 0);
    du0DramWrFifoFull : in std_logic;
    du0DramWrFifoMaskData : out std_logic_vector(31 downto 0);
    du0DramWrFifoWrEn : out std_logic;
    du1DramAddrFifoAddr : out std_logic_vector(28 downto 0);
    du1DramAddrFifoCmd : out std_logic_vector(2 downto 0);
    du1DramAddrFifoFull : in std_logic;
    du1DramAddrFifoWrEn : out std_logic;
    du1DramPhyInitDone : in std_logic;
    du1DramRdDataValid : in std_logic;
    du1DramRdFifoDataOut : in std_logic_vector(255 downto 0);
    du1DramWrFifoDataIn : out std_logic_vector(255 downto 0);
    du1DramWrFifoFull : in std_logic;
    du1DramWrFifoMaskData : out std_logic_vector(31 downto 0);
    du1DramWrFifoWrEn : out std_logic;
    abBusResetTrigger : in std_logic;
    aIntClk10Trigger : in std_logic;
    aPxiStarData : in std_logic;
    aPxiTrigDataIn : in std_logic_vector(7 downto 0);
    aPxiTrigDataOut : out std_logic_vector(7 downto 0);
    aPxiTrigDataTri : out std_logic_vector(7 downto 0);
    bRoutingClipNiCompatible : out std_logic;
    bRoutingClipPresent : out std_logic;
    bTriggerRoutingBaRegPortInAddress : in std_logic_vector(27 downto 0);
    bTriggerRoutingBaRegPortInData : in std_logic_vector(63 downto 0);
    bTriggerRoutingBaRegPortInRdStrobe : in std_logic_vector(7 downto 0);
    bTriggerRoutingBaRegPortInWtStrobe : in std_logic_vector(7 downto 0);
    bTriggerRoutingBaRegPortOutAck : out std_logic;
    bTriggerRoutingBaRegPortOutData : out std_logic_vector(63 downto 0);
    BusClkTrigger : in std_logic;
    dDevClkEn : in std_logic;
    dTdcAssert : out std_logic;
    pIntSync100Trigger : in std_logic;
    PxieClk100Trigger : in std_logic;
    sTdcDeassert : out std_logic;


    -----------------------------------
    -- Clocks from TheWindow
    -----------------------------------
    TopLevelClkOut : out std_logic;
    ReliableClkOut : out std_logic;

    -----------------------------------
    -- Diagram/Reset/Clock status
    -----------------------------------
    rBaseClksValid : in std_logic := '1';
    tDiagramActive : out std_logic;
    rDiagramReset : out std_logic;
    aDiagramReset : out std_logic;
    rDerivedClockLostLockError : out std_logic;
    rGatedBaseClksValid : in std_logic := '1';
    aSafeToEnableGatedClks : out std_logic
  );

end TheWindow;

architecture behavioral of TheWindow is

   ----------------------------------
   -- signals for I/O nodes & clocks
   ----------------------------------
     signal internal_pIntSync100_din: std_logic_vector(0 downto 0);
  signal internal_aIntClk10_din: std_logic_vector(0 downto 0);
  signal internal_aDramReady_din: std_logic_vector(0 downto 0);

     signal internal_Routing_aSource0: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource1: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource2: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource3: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource4: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource5: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource6: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource7: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource8: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource9: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource10: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource11: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource12: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource13: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource14: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource15: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource16: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource17: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource18: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource19: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource20: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource21: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource22: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource23: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource24: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource25: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource26: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource27: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource28: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource29: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource30: std_logic_vector(0 downto 0);
  signal internal_Routing_aSource31: std_logic_vector(0 downto 0);
  signal internal_Routing_TClk: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestinationSyncPulse: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination0: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination1: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination2: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination3: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination4: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination5: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination6: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination7: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination8: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination9: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination10: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination11: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination12: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination13: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination14: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination15: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination16: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination17: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination18: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination19: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination20: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination21: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination22: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination23: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination24: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination25: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination26: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination27: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination28: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination29: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination30: std_logic_vector(0 downto 0);
  signal internal_Routing_aDestination31: std_logic_vector(0 downto 0);
  signal internal_Routing_aDiagramIdentity:  std_logic_vector(31 downto 0);
  signal internal_Routing_aClipIdentity:  std_logic_vector(7 downto 0);

   
   

           signal PxieClk100ThruBuf : std_logic;
        signal DmaClkThruBuf : std_logic;
        signal BusClkThruBuf : std_logic;
        signal ReliableClkInThruBuf : std_logic;
        signal PllClk80ThruBuf : std_logic;
        signal ReliableClk : std_logic;
        signal TopLvClk : std_logic;


   ------------------------
   -- signals for diagram
   ------------------------
   signal tDiagramEnableOut, tDiagramEnableIn, tDiagramEnableClear : std_logic;
   signal rDiagramResetStatus : std_logic;
   signal rDiagramResetLoc, aDiagramResetLoc : std_logic;
   signal aSafeToEnableGatedClksLoc : std_logic;
   signal rGatedClkIsRunning : std_logic;
   signal rInternalClksValid : std_logic;
   signal rEnableClksForViRun : std_logic;
   signal rGatedBaseClkStartupErr : std_logic;
   signal rDiagramResetAssertionErr : std_logic;
   signal rGatedBaseClksValidLoc : std_logic;

   ------------------------
   -- signals for DCM
   ------------------------
   signal rDerivedClkStartupErr : std_logic;
   signal rDcmPllSourceClksValid : std_logic;
   signal rDerivedClksValid : std_logic;

   ---------------------------------------
   -- signals for communication interface
   ---------------------------------------
   signal bRegPortOutFlat : std_logic_vector(kRegPortOutSize-1 downto 0);
   signal bRegPortInFlat : std_logic_vector(kRegPortInSize-1 downto 0);

   signal bBusReset, bBusReset_ms : std_logic := '0';

   attribute ASYNC_REG : string;
   attribute ASYNC_REG of bBusReset_ms,bBusReset: signal is "true";
   
   signal rAssumeExternalClkInvalid : std_logic;
	 signal rDerivedFromExternalValid : std_logic;

   signal dInputStreamInterfaceToFifoFlat : std_logic_vector(InputStreamInterfaceToFifoFlat_t'length*
     Larger(kNumberOfDmaChannels,1)-1 downto 0);
   signal dInputStreamInterfaceFromFifoFlat : std_logic_vector(InputStreamInterfaceFromFifoFlat_t'length*
     Larger(kNumberOfDmaChannels,1)-1 downto 0);
   signal dOutputStreamInterfaceToFifoFlat : std_logic_vector(OutputStreamInterfaceToFifoFlat_t'length*
     Larger(kNumberOfDmaChannels,1)-1 downto 0);
   signal dOutputStreamInterfaceFromFifoFlat : std_logic_vector(OutputStreamInterfaceFromFifoFlat_t'length*
     Larger(kNumberOfDmaChannels,1)-1 downto 0);
   signal bIrqToInterfaceFlat : std_logic_vector(66*Larger(kNumberOfIrqs,1)-1
     downto 0);

   signal dNiFpgaMasterWriteRequestFromMasterArrayFlat : std_logic_vector(
      NiFpgaMasterWriteRequestFromMasterFlat_t'length * Larger(kNumberOfMasterPorts,1)-1 downto 0);
   signal dNiFpgaMasterWriteRequestToMasterArrayFlat : std_logic_vector(
      NiFpgaMasterWriteRequestToMasterFlat_t'length * Larger(kNumberOfMasterPorts,1)-1 downto 0);
   signal dNiFpgaMasterWriteDataFromMasterArrayFlat : std_logic_vector(
      NiFpgaMasterWriteDataFromMasterFlat_t'length * Larger(kNumberOfMasterPorts,1)-1 downto 0);
   signal dNiFpgaMasterWriteDataToMasterArrayFlat : std_logic_vector(
      NiFpgaMasterWriteDataToMasterFlat_t'length * Larger(kNumberOfMasterPorts,1)-1 downto 0);
   signal dNiFpgaMasterWriteStatusToMasterArrayFlat : std_logic_vector(
      NiFpgaMasterWriteStatusToMasterFlat_t'length * Larger(kNumberOfMasterPorts,1)-1 downto 0);

   signal dNiFpgaMasterReadRequestFromMasterArrayFlat : std_logic_vector(
      NiFpgaMasterReadRequestFromMasterFlat_t'length * Larger(kNumberOfMasterPorts,1)-1 downto 0);
   signal dNiFpgaMasterReadRequestToMasterArrayFlat : std_logic_vector(
      NiFpgaMasterReadRequestToMasterFlat_t'length * Larger(kNumberOfMasterPorts,1)-1 downto 0);
   signal dNiFpgaMasterReadDataToMasterArrayFlat : std_logic_vector(
      NiFpgaMasterReadDataToMasterFlat_t'length * Larger(kNumberOfMasterPorts,1)-1 downto 0);
begin

   --------------------------------
   -- logic for I/O nodes & clocks
   --------------------------------
     internal_pIntSync100_din(0) <= to_X01(pIntSync100);
  internal_aIntClk10_din(0) <= to_X01(aIntClk10);
  internal_aDramReady_din(0) <= to_X01(aDramReady);
internal_Routing_aSource0 <= (others => '0');
internal_Routing_aSource1 <= (others => '0');
internal_Routing_aSource2 <= (others => '0');
internal_Routing_aSource3 <= (others => '0');
internal_Routing_aSource4 <= (others => '0');
internal_Routing_aSource5 <= (others => '0');
internal_Routing_aSource6 <= (others => '0');
internal_Routing_aSource7 <= (others => '0');
internal_Routing_aSource8 <= (others => '0');
internal_Routing_aSource9 <= (others => '0');
internal_Routing_aSource10 <= (others => '0');
internal_Routing_aSource11 <= (others => '0');
internal_Routing_aSource12 <= (others => '0');
internal_Routing_aSource13 <= (others => '0');
internal_Routing_aSource14 <= (others => '0');
internal_Routing_aSource15 <= (others => '0');
internal_Routing_aSource16 <= (others => '0');
internal_Routing_aSource17 <= (others => '0');
internal_Routing_aSource18 <= (others => '0');
internal_Routing_aSource19 <= (others => '0');
internal_Routing_aSource20 <= (others => '0');
internal_Routing_aSource21 <= (others => '0');
internal_Routing_aSource22 <= (others => '0');
internal_Routing_aSource23 <= (others => '0');
internal_Routing_aSource24 <= (others => '0');
internal_Routing_aSource25 <= (others => '0');
internal_Routing_aSource26 <= (others => '0');
internal_Routing_aSource27 <= (others => '0');
internal_Routing_aSource28 <= (others => '0');
internal_Routing_aSource29 <= (others => '0');
internal_Routing_aSource30 <= (others => '0');
internal_Routing_aSource31 <= (others => '0');
internal_Routing_aDiagramIdentity <= (others => '0');

         bdAxiStreamRdToClipTReady <= '0';
      bdAxiStreamWrToClipTData <= (others =>'0');
      bdAxiStreamWrToClipTLast <= '0';
      bdAxiStreamWrToClipTValid <= '0';
      bdIFifoRdData <= (others =>'0');
      bdIFifoRdDataValid <= '0';
      bdIFifoRdIsError <= '0';
      bdIFifoWrReadyForOutput <= '0';


     TopLvClk <= PllClk80;
  ReliableClk <= ReliableClkIn;
        rDerivedClksValid <=  '1';
        rDerivedFromExternalValid <=  '0';
   rDerivedClkStartupErr <= '0';

PxieClk100ThruBuf <= PxieClk100;
DmaClkThruBuf <= DmaClk;
BusClkThruBuf <= BusClk;
ReliableClkInThruBuf <= ReliableClkIn;
PllClk80ThruBuf <= PllClk80;
   rGatedBaseClksValidLoc <= rGatedBaseClksValid;
   rGatedBaseClkStartupErr <= '0';


   
   

   ---------------------------------------------------------------------------
   --If we have internally-accessed socket signals (e.g. Execute
   --Disable for the ML510 target) assign the local signals here
   ---------------------------------------------------------------------------
   

   ----------------------------------------------------------------------------
   -- Decompress the flattened communication interface signals.
   -- A ViControl overlay may be instantiated here
   ----------------------------------------------------------------------------

   bRegPortOut <= BuildRegPortOut(bRegPortOutFlat);
   bRegPortInFlat <= to_StdLogicVector(bRegPortIn);

   dInputStreamInterfaceToFifoFlat <= StreamInterfaceArrayToVector(
     FlattenStreamInterface(dInputStreamInterfaceToFifo));
   dOutputStreamInterfaceToFifoFlat <= StreamInterfaceArrayToVector(
     FlattenStreamInterface(dOutputStreamInterfaceToFifo));

   dInputStreamInterfaceFromFifo <= UnflattenStreamInterface(StreamInterfaceVectorToArray(
    ArraySize => dInputStreamInterfaceFromFifo'length,
    Vector => dInputStreamInterfaceFromFifoFlat));
   dOutputStreamInterfaceFromFifo <= UnflattenStreamInterface(StreamInterfaceVectorToArray(
    ArraySize => dOutputStreamInterfaceFromFifo'length,
    Vector => dOutputStreamInterfaceFromFifoFlat));
   bIrqToInterface <= BuildIrqToInterfaceArray(bIrqToInterfaceFlat);
   dNiFpgaMasterWriteRequestFromMaster <= UnflattenMasterPortInterface(
     MasterPortInterfaceVectorToArray(
     ArraySize => dNiFpgaMasterWriteRequestFromMaster'length,
     Vector => dNiFpgaMasterWriteRequestFromMasterArrayFlat));
   dNiFpgaMasterWriteRequestToMasterArrayFlat <= MasterPortInterfaceArrayToVector(
     FlattenMasterPortInterface(dNiFpgaMasterWriteRequestToMaster));
   dNiFpgaMasterWriteDataFromMaster <= UnflattenMasterPortInterface(
     MasterPortInterfaceVectorToArray(
     ArraySize => dNiFpgaMasterWriteDataFromMaster'length,
     Vector => dNiFpgaMasterWriteDataFromMasterArrayFlat));
   dNiFpgaMasterWriteDataToMasterArrayFlat <= MasterPortInterfaceArrayToVector(
     FlattenMasterPortInterface(dNiFpgaMasterWriteDataToMaster));
   dNiFpgaMasterWriteStatusToMasterArrayFlat <= MasterPortInterfaceArrayToVector(
     FlattenMasterPortInterface(dNiFpgaMasterWriteStatusToMaster));

   dNiFpgaMasterReadRequestFromMaster <= UnflattenMasterPortInterface(
     MasterPortInterfaceVectorToArray(
     ArraySize => dNiFpgaMasterReadRequestFromMaster'length,
     Vector => dNiFpgaMasterReadRequestFromMasterArrayFlat));
   dNiFpgaMasterReadRequestToMasterArrayFlat <= MasterPortInterfaceArrayToVector(
     FlattenMasterPortInterface(dNiFpgaMasterReadRequestToMaster));
   dNiFpgaMasterReadDataToMasterArrayFlat <= MasterPortInterfaceArrayToVector(
     FlattenMasterPortInterface(dNiFpgaMasterReadDataToMaster));

   -------------------------------------------------------------------------
   -- This process synchronizes the async bus reset to the bus clock domain
   -------------------------------------------------------------------------
   SynchronizeBusReset : process(BusClkThruBuf)
   begin
     if rising_edge(BusClkThruBuf) then
       bBusReset_ms <= to_StdLogic(aBusReset);
       bBusReset <= bBusReset_ms;
     end if;
   end process SynchronizeBusReset;

   -----------
   -- the VI
   -----------
   theVI : entity work.NiFpgaAG_BlankRunningVI (vhdl_labview)
      port map(
         
         
         

         		   DmaClk => DmaClk,
		   BusClk => BusClk,
		   ReliableClkIn => ReliableClkIn,
		   PllClk80 => PllClk80,


         

         TopLvClk       => TopLvClk, -- to be deleted when CAR 3LHF5CMO is fixed

         enable_in                  =>  tDiagramEnableIn ,
         enable_out                 =>  tDiagramEnableOut,
         enable_clr                 =>  tDiagramEnableClear,
         tDiagramEnableIn           =>  tDiagramEnableIn ,
         tDiagramEnableOut          =>  tDiagramEnableOut,
         tDiagramEnableClear        =>  tDiagramEnableClear,
         bCommunicationTimeoutIn    =>  to_stdlogic(bRegPortTimeout),

         rDiagramResetOut           =>  rDiagramResetLoc,
         rDiagramResetIn            =>  rDiagramResetLoc,

         aDiagramResetOut           =>  aDiagramResetLoc,
         reset                      =>  aDiagramResetLoc,

         aBusReset                  => to_StdLogic(aBusReset),
         bBusReset                  => bBusReset,
         bIoWtToEnSafeBusCrossing   => '1',

         bRegPortOut                => bRegPortOutFlat,
         bRegPortIn                 => bRegPortInFlat,

         dInputStreamInterfaceToFifo    => dInputStreamInterfaceToFifoFlat,
         dInputStreamInterfaceFromFifo  => dInputStreamInterfaceFromFifoFlat,
         dOutputStreamInterfaceToFifo   => dOutputStreamInterfaceToFifoFlat,
         dOutputStreamInterfaceFromFifo => dOutputStreamInterfaceFromFifoFlat,
         bIrqToInterface => bIrqToInterfaceFlat,
         dNiFpgaMasterWriteRequestFromMaster   => dNiFpgaMasterWriteRequestFromMasterArrayFlat,
         dNiFpgaMasterWriteRequestToMaster     => dNiFpgaMasterWriteRequestToMasterArrayFlat,
         dNiFpgaMasterWriteDataFromMaster      => dNiFpgaMasterWriteDataFromMasterArrayFlat,
         dNiFpgaMasterWriteDataToMaster        => dNiFpgaMasterWriteDataToMasterArrayFlat,
         dNiFpgaMasterWriteStatusToMaster      => dNiFpgaMasterWriteStatusToMasterArrayFlat,
         dNiFpgaMasterReadRequestFromMaster    => dNiFpgaMasterReadRequestFromMasterArrayFlat,
         dNiFpgaMasterReadRequestToMaster      => dNiFpgaMasterReadRequestToMasterArrayFlat,
         dNiFpgaMasterReadDataToMaster         => dNiFpgaMasterReadDataToMasterArrayFlat,

         rBaseClksValid               => rBaseClksValid,
         rGatedBaseClksValid          => rGatedBaseClksValidLoc,
         rSafeToEnableGatedClks       => aSafeToEnableGatedClksLoc,
         rGatedBaseClkStartupErr      => rGatedBaseClkStartupErr,
         rDcmPllSourceClksValidOut    => rDcmPllSourceClksValid,
         rDerivedClksValid            => rDerivedClksValid,
         rDerivedClockLostLockError   => rDerivedClockLostLockError,
         rDiagramResetStatusIn        => rDiagramResetStatus,
         rDiagramResetStatusOut       => rDiagramResetStatus,
         rInternalClksValidIn         => rInternalClksValid,
         rInternalClksValidOut        => rInternalClksValid,
         rEnableClksForViRunIn        => rEnableClksForViRun,
         rEnableClksForViRunOut       => rEnableClksForViRun,
         rDerivedClkStartupErr        => rDerivedClkStartupErr,
         rDiagramResetAssertionErrIn  => rDiagramResetAssertionErr,
         rDiagramResetAssertionErrOut => rDiagramResetAssertionErr,
         rAssumeExternalClkInvalid    => rAssumeExternalClkInvalid,
			   rDerivedFromExternalValid    => rDerivedFromExternalValid
      );

  --------------
  -- CLIP nodes
  --------------
   theCLIPs: entity work.NiLvFpgaClipContainer (ClipContainer_VHDL)
  port map(
  Dram0ClkSocket => Dram0ClkSocket,
  du0DramAddrFifoAddr => du0DramAddrFifoAddr,
  du0DramAddrFifoCmd => du0DramAddrFifoCmd,
  du0DramAddrFifoFull => du0DramAddrFifoFull,
  du0DramAddrFifoWrEn => du0DramAddrFifoWrEn,
  du0DramPhyInitDone => du0DramPhyInitDone,
  du0DramRdDataValid => du0DramRdDataValid,
  du0DramRdFifoDataOut => du0DramRdFifoDataOut,
  du0DramWrFifoDataIn => du0DramWrFifoDataIn,
  du0DramWrFifoFull => du0DramWrFifoFull,
  du0DramWrFifoMaskData => du0DramWrFifoMaskData,
  du0DramWrFifoWrEn => du0DramWrFifoWrEn,
  Dram1ClkSocket => Dram1ClkSocket,
  du1DramAddrFifoAddr => du1DramAddrFifoAddr,
  du1DramAddrFifoCmd => du1DramAddrFifoCmd,
  du1DramAddrFifoFull => du1DramAddrFifoFull,
  du1DramAddrFifoWrEn => du1DramAddrFifoWrEn,
  du1DramPhyInitDone => du1DramPhyInitDone,
  du1DramRdDataValid => du1DramRdDataValid,
  du1DramRdFifoDataOut => du1DramRdFifoDataOut,
  du1DramWrFifoDataIn => du1DramWrFifoDataIn,
  du1DramWrFifoFull => du1DramWrFifoFull,
  du1DramWrFifoMaskData => du1DramWrFifoMaskData,
  du1DramWrFifoWrEn => du1DramWrFifoWrEn,
  abBusResetTrigger => abBusResetTrigger,
  aIntClk10Trigger => aIntClk10Trigger,
  aPxiStarData => aPxiStarData,
  aPxiTrigDataIn => aPxiTrigDataIn,
  aPxiTrigDataOut => aPxiTrigDataOut,
  aPxiTrigDataTri => aPxiTrigDataTri,
  bRoutingClipNiCompatible => bRoutingClipNiCompatible,
  bRoutingClipPresent => bRoutingClipPresent,
  bTriggerRoutingBaRegPortInAddress => bTriggerRoutingBaRegPortInAddress,
  bTriggerRoutingBaRegPortInData => bTriggerRoutingBaRegPortInData,
  bTriggerRoutingBaRegPortInRdStrobe => bTriggerRoutingBaRegPortInRdStrobe,
  bTriggerRoutingBaRegPortInWtStrobe => bTriggerRoutingBaRegPortInWtStrobe,
  bTriggerRoutingBaRegPortOutAck => bTriggerRoutingBaRegPortOutAck,
  bTriggerRoutingBaRegPortOutData => bTriggerRoutingBaRegPortOutData,
  BusClkTrigger => BusClkTrigger,
  dDevClkEn => dDevClkEn,
  dTdcAssert => dTdcAssert,
  pIntSync100Trigger => pIntSync100Trigger,
  PxieClk100Trigger => PxieClk100Trigger,
  sTdcDeassert => sTdcDeassert,

Routing_DataClk => PllClk80,
Routing_SyncPulseClk => PxieClk100,
Routing_aSource0 => internal_Routing_aSource0,
Routing_aSource1 => internal_Routing_aSource1,
Routing_aSource2 => internal_Routing_aSource2,
Routing_aSource3 => internal_Routing_aSource3,
Routing_aSource4 => internal_Routing_aSource4,
Routing_aSource5 => internal_Routing_aSource5,
Routing_aSource6 => internal_Routing_aSource6,
Routing_aSource7 => internal_Routing_aSource7,
Routing_aSource8 => internal_Routing_aSource8,
Routing_aSource9 => internal_Routing_aSource9,
Routing_aSource10 => internal_Routing_aSource10,
Routing_aSource11 => internal_Routing_aSource11,
Routing_aSource12 => internal_Routing_aSource12,
Routing_aSource13 => internal_Routing_aSource13,
Routing_aSource14 => internal_Routing_aSource14,
Routing_aSource15 => internal_Routing_aSource15,
Routing_aSource16 => internal_Routing_aSource16,
Routing_aSource17 => internal_Routing_aSource17,
Routing_aSource18 => internal_Routing_aSource18,
Routing_aSource19 => internal_Routing_aSource19,
Routing_aSource20 => internal_Routing_aSource20,
Routing_aSource21 => internal_Routing_aSource21,
Routing_aSource22 => internal_Routing_aSource22,
Routing_aSource23 => internal_Routing_aSource23,
Routing_aSource24 => internal_Routing_aSource24,
Routing_aSource25 => internal_Routing_aSource25,
Routing_aSource26 => internal_Routing_aSource26,
Routing_aSource27 => internal_Routing_aSource27,
Routing_aSource28 => internal_Routing_aSource28,
Routing_aSource29 => internal_Routing_aSource29,
Routing_aSource30 => internal_Routing_aSource30,
Routing_aSource31 => internal_Routing_aSource31,
Routing_TClk => internal_Routing_TClk,
Routing_aDestinationSyncPulse => internal_Routing_aDestinationSyncPulse,
Routing_aDestination0 => internal_Routing_aDestination0,
Routing_aDestination1 => internal_Routing_aDestination1,
Routing_aDestination2 => internal_Routing_aDestination2,
Routing_aDestination3 => internal_Routing_aDestination3,
Routing_aDestination4 => internal_Routing_aDestination4,
Routing_aDestination5 => internal_Routing_aDestination5,
Routing_aDestination6 => internal_Routing_aDestination6,
Routing_aDestination7 => internal_Routing_aDestination7,
Routing_aDestination8 => internal_Routing_aDestination8,
Routing_aDestination9 => internal_Routing_aDestination9,
Routing_aDestination10 => internal_Routing_aDestination10,
Routing_aDestination11 => internal_Routing_aDestination11,
Routing_aDestination12 => internal_Routing_aDestination12,
Routing_aDestination13 => internal_Routing_aDestination13,
Routing_aDestination14 => internal_Routing_aDestination14,
Routing_aDestination15 => internal_Routing_aDestination15,
Routing_aDestination16 => internal_Routing_aDestination16,
Routing_aDestination17 => internal_Routing_aDestination17,
Routing_aDestination18 => internal_Routing_aDestination18,
Routing_aDestination19 => internal_Routing_aDestination19,
Routing_aDestination20 => internal_Routing_aDestination20,
Routing_aDestination21 => internal_Routing_aDestination21,
Routing_aDestination22 => internal_Routing_aDestination22,
Routing_aDestination23 => internal_Routing_aDestination23,
Routing_aDestination24 => internal_Routing_aDestination24,
Routing_aDestination25 => internal_Routing_aDestination25,
Routing_aDestination26 => internal_Routing_aDestination26,
Routing_aDestination27 => internal_Routing_aDestination27,
Routing_aDestination28 => internal_Routing_aDestination28,
Routing_aDestination29 => internal_Routing_aDestination29,
Routing_aDestination30 => internal_Routing_aDestination30,
Routing_aDestination31 => internal_Routing_aDestination31,
Routing_aDiagramIdentity => internal_Routing_aDiagramIdentity,
Routing_aClipIdentity => internal_Routing_aClipIdentity,

aClockGate=> aSafeToEnableGatedClksLoc,
aReset => aDiagramResetLoc
);


  -----------------------------------
  -- Misc signals for the TopLevel
  -----------------------------------
  rDiagramReset  <= rDiagramResetLoc;
  aDiagramReset  <= aDiagramResetLoc;
  ReliableClkOut <= ReliableClk;
  TopLevelClkOut <= TopLvClk;
  aSafeToEnableGatedClks <= aSafeToEnableGatedClksLoc;
  -- Indicates whether or not the diagram is running. This does
  -- not indicate status of CLIP nodes.
  tDiagramActive <= tDiagramEnableIn and not tDiagramEnableOut;

end architecture behavioral;
